package com.model1.newAdd;
// Generated 2018-4-23 15:53:37 by Hibernate Tools 3.4.0.CR1

/**
 * CarSeries generated by hbm2java
 */
public class CarSeries implements java.io.Serializable {

	private Integer id;
	private Integer brandId;
	private String name;
	private String alias;
	private String groupName;
	private String logo;
	private String imgurl;
	private byte status;
	private Integer createTime;
	private Integer updateTime;
	private Integer id1;
	private String namepy;
	private String tpTitle;

	public CarSeries() {
	}

	public CarSeries(byte status) {
		this.status = status;
	}

	public CarSeries(Integer brandId, String name, String alias, String groupName, String logo, String imgurl,
			byte status, Integer createTime, Integer updateTime, Integer id1, String namepy, String tpTitle) {
		this.brandId = brandId;
		this.name = name;
		this.alias = alias;
		this.groupName = groupName;
		this.logo = logo;
		this.imgurl = imgurl;
		this.status = status;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.id1 = id1;
		this.namepy = namepy;
		this.tpTitle = tpTitle;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getBrandId() {
		return this.brandId;
	}

	public void setBrandId(Integer brandId) {
		this.brandId = brandId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public String getLogo() {
		return this.logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	public String getImgurl() {
		return this.imgurl;
	}

	public void setImgurl(String imgurl) {
		this.imgurl = imgurl;
	}

	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	public Integer getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Integer createTime) {
		this.createTime = createTime;
	}

	public Integer getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Integer updateTime) {
		this.updateTime = updateTime;
	}

	public Integer getId1() {
		return this.id1;
	}

	public void setId1(Integer id1) {
		this.id1 = id1;
	}

	public String getNamepy() {
		return this.namepy;
	}

	public void setNamepy(String namepy) {
		this.namepy = namepy;
	}

	public String getTpTitle() {
		return this.tpTitle;
	}

	public void setTpTitle(String tpTitle) {
		this.tpTitle = tpTitle;
	}

}
