 <%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
  <%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
    <%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %> 
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %> 
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<div  class="ng-scope">
<script>
function IdCard(UUserCard,num){
if(num==1){
//获取出生日期
birth=UUserCard.substring(6, 10) + "-" + UUserCard.substring(10, 12) + "-" + UUserCard.substring(12, 14);
return birth;
}
if(num==2){
//获取性别
if (parseInt(UUserCard.substr(16, 1)) % 2 == 1) {
//男
return "男";
} else {
//女
return "女";
}
}
if(num==3){
//获取年龄
var myDate = new Date();
var month = myDate.getMonth() + 1;
var day = myDate.getDate();
var age = myDate.getFullYear() - UUserCard.substring(6, 10) - 1;
if (UUserCard.substring(10, 12) < month || UUserCard.substring(10, 12) == month && UUserCard.substring(12, 14) <= day) {
age++;
}
return age;
}
}

</script>
<script type="text/javascript">
$(document).ready(function () {
   var c_name="${pd.c_name }";
   var c_card="${pd.c_cardno}";
  // alert(c_card+"-"+c_name);
   if(c_name!=''){
	 document.getElementById("englishname").value=makePy(c_name);
    }
   if(c_card!=''){
	   if(isCardNo(c_card)==true){
		   document.getElementById("birthday").value=IdCard(c_card,1);
	   } 
   }
});

function isCardNo(card) 
{ 
  // 身份证号码为15位或者18位，15位时全为数字，18位前17位为数字，最后一位是校验位，可能为数字或字符X 
  var reg = /(^\d{15}$)|(^\d{18}$)|(^\d{17}(\d|X|x)$)/; 
  if(reg.test(card) === false) 
  { 
    return false; 
  }
	return true; 
  
}

//汉字拼音首字母列表 本列表包含了20902个汉字,用于配合 ToChineseSpell  
//函数使用,本表收录的字符的Unicode编码范围为19968至40869, XDesigner 整理  
var strChineseFirstPY = "YDYQSXMWZSSXJBYMGCCZQPSSQBYCDSCDQLDYLYBSSJGYZZJJFKCCLZDHWDWZJLJPFYYNWJJTMYHZWZHFLZPPQHGSCYYYNJQYXXGJHHSDSJNKKTMOMLCRXYPSNQSECCQZGGLLYJLMYZZSECYKYYHQWJSSGGYXYZYJWWKDJHYCHMYXJTLXJYQBYXZLDWRDJRWYSRLDZJPCBZJJBRCFTLECZSTZFXXZHTRQHYBDLYCZSSYMMRFMYQZPWWJJYFCRWFDFZQPYDDWYXKYJAWJFFXYPSFTZYHHYZYSWCJYXSCLCXXWZZXNBGNNXBXLZSZSBSGPYSYZDHMDZBQBZCWDZZYYTZHBTSYYBZGNTNXQYWQSKBPHHLXGYBFMJEBJHHGQTJCYSXSTKZHLYCKGLYSMZXYALMELDCCXGZYRJXSDLTYZCQKCNNJWHJTZZCQLJSTSTBNXBTYXCEQXGKWJYFLZQLYHYXSPSFXLMPBYSXXXYDJCZYLLLSJXFHJXPJBTFFYABYXBHZZBJYZLWLCZGGBTSSMDTJZXPTHYQTGLJSCQFZKJZJQNLZWLSLHDZBWJNCJZYZSQQYCQYRZCJJWYBRTWPYFTWEXCSKDZCTBZHYZZYYJXZCFFZZMJYXXSDZZOTTBZLQWFCKSZSXFYRLNYJMBDTHJXSQQCCSBXYYTSYFBXDZTGBCNSLCYZZPSAZYZZSCJCSHZQYDXLBPJLLMQXTYDZXSQJTZPXLCGLQTZWJBHCTSYJSFXYEJJTLBGXSXJMYJQQPFZASYJNTYDJXKJCDJSZCBARTDCLYJQMWNQNCLLLKBYBZZSYHQQLTWLCCXTXLLZNTYLNEWYZYXCZXXGRKRMTCNDNJTSYYSSDQDGHSDBJGHRWRQLYBGLXHLGTGXBQJDZPYJSJYJCTMRNYMGRZJCZGJMZMGXMPRYXKJNYMSGMZJYMKMFXMLDTGFBHCJHKYLPFMDXLQJJSMTQGZSJLQDLDGJYCALCMZCSDJLLNXDJFFFFJCZFMZFFPFKHKGDPSXKTACJDHHZDDCRRCFQYJKQCCWJDXHWJLYLLZGCFCQDSMLZPBJJPLSBCJGGDCKKDEZSQCCKJGCGKDJTJDLZYCXKLQSCGJCLTFPCQCZGWPJDQYZJJBYJHSJDZWGFSJGZKQCCZLLPSPKJGQJHZZLJPLGJGJJTHJJYJZCZMLZLYQBGJWMLJKXZDZNJQSYZMLJLLJKYWXMKJLHSKJGBMCLYYMKXJQLBMLLKMDXXKWYXYSLMLPSJQQJQXYXFJTJDXMXXLLCXQBSYJBGWYMBGGBCYXPJYGPEPFGDJGBHBNSQJYZJKJKHXQFGQZKFHYGKHDKLLSDJQXPQYKYBNQSXQNSZSWHBSXWHXWBZZXDMNSJBSBKBBZKLYLXGWXDRWYQZMYWSJQLCJXXJXKJEQXSCYETLZHLYYYSDZPAQYZCMTLSHTZCFYZYXYLJSDCJQAGYSLCQLYYYSHMRQQKLDXZSCSSSYDYCJYSFSJBFRSSZQSBXXPXJYSDRCKGJLGDKZJZBDKTCSYQPYHSTCLDJDHMXMCGXYZHJDDTMHLTXZXYLYMOHYJCLTYFBQQXPFBDFHHTKSQHZYYWCNXXCRWHOWGYJLEGWDQCWGFJYCSNTMYTOLBYGWQWESJPWNMLRYDZSZTXYQPZGCWXHNGPYXSHMYQJXZTDPPBFYHZHTJYFDZWKGKZBLDNTSXHQEEGZZYLZMMZYJZGXZXKHKSTXNXXWYLYAPSTHXDWHZYMPXAGKYDXBHNHXKDPJNMYHYLPMGOCSLNZHKXXLPZZLBMLSFBHHGYGYYGGBHSCYAQTYWLXTZQCEZYDQDQMMHTKLLSZHLSJZWFYHQSWSCWLQAZYNYTLSXTHAZNKZZSZZLAXXZWWCTGQQTDDYZTCCHYQZFLXPSLZYGPZSZNGLNDQTBDLXGTCTAJDKYWNSYZLJHHZZCWNYYZYWMHYCHHYXHJKZWSXHZYXLYSKQYSPSLYZWMYPPKBYGLKZHTYXAXQSYSHXASMCHKDSCRSWJPWXSGZJLWWSCHSJHSQNHCSEGNDAQTBAALZZMSSTDQJCJKTSCJAXPLGGXHHGXXZCXPDMMHLDGTYBYSJMXHMRCPXXJZCKZXSHMLQXXTTHXWZFKHCCZDYTCJYXQHLXDHYPJQXYLSYYDZOZJNYXQEZYSQYAYXWYPDGXDDXSPPYZNDLTWRHXYDXZZJHTCXMCZLHPYYYYMHZLLHNXMYLLLMDCPPXHMXDKYCYRDLTXJCHHZZXZLCCLYLNZSHZJZZLNNRLWHYQSNJHXYNTTTKYJPYCHHYEGKCTTWLGQRLGGTGTYGYHPYHYLQYQGCWYQKPYYYTTTTLHYHLLTYTTSPLKYZXGZWGPYDSSZZDQXSKCQNMJJZZBXYQMJRTFFBTKHZKBXLJJKDXJTLBWFZPPTKQTZTGPDGNTPJYFALQMKGXBDCLZFHZCLLLLADPMXDJHLCCLGYHDZFGYDDGCYYFGYDXKSSEBDHYKDKDKHNAXXYBPBYYHXZQGAFFQYJXDMLJCSQZLLPCHBSXGJYNDYBYQSPZWJLZKSDDTACTBXZDYZYPJZQSJNKKTKNJDJGYYPGTLFYQKASDNTCYHBLWDZHBBYDWJRYGKZYHEYYFJMSDTYFZJJHGCXPLXHLDWXXJKYTCYKSSSMTWCTTQZLPBSZDZWZXGZAGYKTYWXLHLSPBCLLOQMMZSSLCMBJCSZZKYDCZJGQQDSMCYTZQQLWZQZXSSFPTTFQMDDZDSHDTDWFHTDYZJYQJQKYPBDJYYXTLJHDRQXXXHAYDHRJLKLYTWHLLRLLRCXYLBWSRSZZSYMKZZHHKYHXKSMDSYDYCJPBZBSQLFCXXXNXKXWYWSDZYQOGGQMMYHCDZTTFJYYBGSTTTYBYKJDHKYXBELHTYPJQNFXFDYKZHQKZBYJTZBXHFDXKDASWTAWAJLDYJSFHBLDNNTNQJTJNCHXFJSRFWHZFMDRYJYJWZPDJKZYJYMPCYZNYNXFBYTFYFWYGDBNZZZDNYTXZEMMQBSQEHXFZMBMFLZZSRXYMJGSXWZJSPRYDJSJGXHJJGLJJYNZZJXHGXKYMLPYYYCXYTWQZSWHWLYRJLPXSLSXMFSWWKLCTNXNYNPSJSZHDZEPTXMYYWXYYSYWLXJQZQXZDCLEEELMCPJPCLWBXSQHFWWTFFJTNQJHJQDXHWLBYZNFJLALKYYJLDXHHYCSTYYWNRJYXYWTRMDRQHWQCMFJDYZMHMYYXJWMYZQZXTLMRSPWWCHAQBXYGZYPXYYRRCLMPYMGKSJSZYSRMYJSNXTPLNBAPPYPYLXYYZKYNLDZYJZCZNNLMZHHARQMPGWQTZMXXMLLHGDZXYHXKYXYCJMFFYYHJFSBSSQLXXNDYCANNMTCJCYPRRNYTYQNYYMBMSXNDLYLYSLJRLXYSXQMLLYZLZJJJKYZZCSFBZXXMSTBJGNXYZHLXNMCWSCYZYFZLXBRNNNYLBNRTGZQYSATSWRYHYJZMZDHZGZDWYBSSCSKXSYHYTXXGCQGXZZSHYXJSCRHMKKBXCZJYJYMKQHZJFNBHMQHYSNJNZYBKNQMCLGQHWLZNZSWXKHLJHYYBQLBFCDSXDLDSPFZPSKJYZWZXZDDXJSMMEGJSCSSMGCLXXKYYYLNYPWWWGYDKZJGGGZGGSYCKNJWNJPCXBJJTQTJWDSSPJXZXNZXUMELPXFSXTLLXCLJXJJLJZXCTPSWXLYDHLYQRWHSYCSQYYBYAYWJJJQFWQCQQCJQGXALDBZZYJGKGXPLTZYFXJLTPADKYQHPMATLCPDCKBMTXYBHKLENXDLEEGQDYMSAWHZMLJTWYGXLYQZLJEEYYBQQFFNLYXRDSCTGJGXYYNKLLYQKCCTLHJLQMKKZGCYYGLLLJDZGYDHZWXPYSJBZKDZGYZZHYWYFQYTYZSZYEZZLYMHJJHTSMQWYZLKYYWZCSRKQYTLTDXWCTYJKLWSQZWBDCQYNCJSRSZJLKCDCDTLZZZACQQZZDDXYPLXZBQJYLZLLLQDDZQJYJYJZYXNYYYNYJXKXDAZWYRDLJYYYRJLXLLDYXJCYWYWNQCCLDDNYYYNYCKCZHXXCCLGZQJGKWPPCQQJYSBZZXYJSQPXJPZBSBDSFNSFPZXHDWZTDWPPTFLZZBZDMYYPQJRSDZSQZSQXBDGCPZSWDWCSQZGMDHZXMWWFYBPDGPHTMJTHZSMMBGZMBZJCFZWFZBBZMQCFMBDMCJXLGPNJBBXGYHYYJGPTZGZMQBQTCGYXJXLWZKYDPDYMGCFTPFXYZTZXDZXTGKMTYBBCLBJASKYTSSQYYMSZXFJEWLXLLSZBQJJJAKLYLXLYCCTSXMCWFKKKBSXLLLLJYXTYLTJYYTDPJHNHNNKBYQNFQYYZBYYESSESSGDYHFHWTCJBSDZZTFDMXHCNJZYMQWSRYJDZJQPDQBBSTJGGFBKJBXTGQHNGWJXJGDLLTHZHHYYYYYYSXWTYYYCCBDBPYPZYCCZYJPZYWCBDLFWZCWJDXXHYHLHWZZXJTCZLCDPXUJCZZZLYXJJTXPHFXWPYWXZPTDZZBDZCYHJHMLXBQXSBYLRDTGJRRCTTTHYTCZWMXFYTWWZCWJWXJYWCSKYBZSCCTZQNHXNWXXKHKFHTSWOCCJYBCMPZZYKBNNZPBZHHZDLSYDDYTYFJPXYNGFXBYQXCBHXCPSXTYZDMKYSNXSXLHKMZXLYHDHKWHXXSSKQYHHCJYXGLHZXCSNHEKDTGZXQYPKDHEXTYKCNYMYYYPKQYYYKXZLTHJQTBYQHXBMYHSQCKWWYLLHCYYLNNEQXQWMCFBDCCMLJGGXDQKTLXKGNQCDGZJWYJJLYHHQTTTNWCHMXCXWHWSZJYDJCCDBQCDGDNYXZTHCQRXCBHZTQCBXWGQWYYBXHMBYMYQTYEXMQKYAQYRGYZSLFYKKQHYSSQYSHJGJCNXKZYCXSBXYXHYYLSTYCXQTHYSMGSCPMMGCCCCCMTZTASMGQZJHKLOSQYLSWTMXSYQKDZLJQQYPLSYCZTCQQPBBQJZCLPKHQZYYXXDTDDTSJCXFFLLCHQXMJLWCJCXTSPYCXNDTJSHJWXDQQJSKXYAMYLSJHMLALYKXCYYDMNMDQMXMCZNNCYBZKKYFLMCHCMLHXRCJJHSYLNMTJZGZGYWJXSRXCWJGJQHQZDQJDCJJZKJKGDZQGJJYJYLXZXXCDQHHHEYTMHLFSBDJSYYSHFYSTCZQLPBDRFRZTZYKYWHSZYQKWDQZRKMSYNBCRXQBJYFAZPZZEDZCJYWBCJWHYJBQSZYWRYSZPTDKZPFPBNZTKLQYHBBZPNPPTYZZYBQNYDCPJMMCYCQMCYFZZDCMNLFPBPLNGQJTBTTNJZPZBBZNJKLJQYLNBZQHKSJZNGGQSZZKYXSHPZSNBCGZKDDZQANZHJKDRTLZLSWJLJZLYWTJNDJZJHXYAYNCBGTZCSSQMNJPJYTYSWXZFKWJQTKHTZPLBHSNJZSYZBWZZZZLSYLSBJHDWWQPSLMMFBJDWAQYZTCJTBNNWZXQXCDSLQGDSDPDZHJTQQPSWLYYJZLGYXYZLCTCBJTKTYCZJTQKBSJLGMGZDMCSGPYNJZYQYYKNXRPWSZXMTNCSZZYXYBYHYZAXYWQCJTLLCKJJTJHGDXDXYQYZZBYWDLWQCGLZGJGQRQZCZSSBCRPCSKYDZNXJSQGXSSJMYDNSTZTPBDLTKZWXQWQTZEXNQCZGWEZKSSBYBRTSSSLCCGBPSZQSZLCCGLLLZXHZQTHCZMQGYZQZNMCOCSZJMMZSQPJYGQLJYJPPLDXRGZYXCCSXHSHGTZNLZWZKJCXTCFCJXLBMQBCZZWPQDNHXLJCTHYZLGYLNLSZZPCXDSCQQHJQKSXZPBAJYEMSMJTZDXLCJYRYYNWJBNGZZTMJXLTBSLYRZPYLSSCNXPHLLHYLLQQZQLXYMRSYCXZLMMCZLTZSDWTJJLLNZGGQXPFSKYGYGHBFZPDKMWGHCXMSGDXJMCJZDYCABXJDLNBCDQYGSKYDQTXDJJYXMSZQAZDZFSLQXYJSJZYLBTXXWXQQZBJZUFBBLYLWDSLJHXJYZJWTDJCZFQZQZZDZSXZZQLZCDZFJHYSPYMPQZMLPPLFFXJJNZZYLSJEYQZFPFZKSYWJJJHRDJZZXTXXGLGHYDXCSKYSWMMZCWYBAZBJKSHFHJCXMHFQHYXXYZFTSJYZFXYXPZLCHMZMBXHZZSXYFYMNCWDABAZLXKTCSHHXKXJJZJSTHYGXSXYYHHHJWXKZXSSBZZWHHHCWTZZZPJXSNXQQJGZYZYWLLCWXZFXXYXYHXMKYYSWSQMNLNAYCYSPMJKHWCQHYLAJJMZXHMMCNZHBHXCLXTJPLTXYJHDYYLTTXFSZHYXXSJBJYAYRSMXYPLCKDUYHLXRLNLLSTYZYYQYGYHHSCCSMZCTZQXKYQFPYYRPFFLKQUNTSZLLZMWWTCQQYZWTLLMLMPWMBZSSTZRBPDDTLQJJBXZCSRZQQYGWCSXFWZLXCCRSZDZMCYGGDZQSGTJSWLJMYMMZYHFBJDGYXCCPSHXNZCSBSJYJGJMPPWAFFYFNXHYZXZYLREMZGZCYZSSZDLLJCSQFNXZKPTXZGXJJGFMYYYSNBTYLBNLHPFZDCYFBMGQRRSSSZXYSGTZRNYDZZCDGPJAFJFZKNZBLCZSZPSGCYCJSZLMLRSZBZZLDLSLLYSXSQZQLYXZLSKKBRXBRBZCYCXZZZEEYFGKLZLYYHGZSGZLFJHGTGWKRAAJYZKZQTSSHJJXDCYZUYJLZYRZDQQHGJZXSSZBYKJPBFRTJXLLFQWJHYLQTYMBLPZDXTZYGBDHZZRBGXHWNJTJXLKSCFSMWLSDQYSJTXKZSCFWJLBXFTZLLJZLLQBLSQMQQCGCZFPBPHZCZJLPYYGGDTGWDCFCZQYYYQYSSCLXZSKLZZZGFFCQNWGLHQYZJJCZLQZZYJPJZZBPDCCMHJGXDQDGDLZQMFGPSYTSDYFWWDJZJYSXYYCZCYHZWPBYKXRYLYBHKJKSFXTZJMMCKHLLTNYYMSYXYZPYJQYCSYCWMTJJKQYRHLLQXPSGTLYYCLJSCPXJYZFNMLRGJJTYZBXYZMSJYJHHFZQMSYXRSZCWTLRTQZSSTKXGQKGSPTGCZNJSJCQCXHMXGGZTQYDJKZDLBZSXJLHYQGGGTHQSZPYHJHHGYYGKGGCWJZZYLCZLXQSFTGZSLLLMLJSKCTBLLZZSZMMNYTPZSXQHJCJYQXYZXZQZCPSHKZZYSXCDFGMWQRLLQXRFZTLYSTCTMJCXJJXHJNXTNRZTZFQYHQGLLGCXSZSJDJLJCYDSJTLNYXHSZXCGJZYQPYLFHDJSBPCCZHJJJQZJQDYBSSLLCMYTTMQTBHJQNNYGKYRQYQMZGCJKPDCGMYZHQLLSLLCLMHOLZGDYYFZSLJCQZLYLZQJESHNYLLJXGJXLYSYYYXNBZLJSSZCQQCJYLLZLTJYLLZLLBNYLGQCHXYYXOXCXQKYJXXXYKLXSXXYQXCYKQXQCSGYXXYQXYGYTQOHXHXPYXXXULCYEYCHZZCBWQBBWJQZSCSZSSLZYLKDESJZWMYMCYTSDSXXSCJPQQSQYLYYZYCMDJDZYWCBTJSYDJKCYDDJLBDJJSODZYSYXQQYXDHHGQQYQHDYXWGMMMAJDYBBBPPBCMUUPLJZSMTXERXJMHQNUTPJDCBSSMSSSTKJTSSMMTRCPLZSZMLQDSDMJMQPNQDXCFYNBFSDQXYXHYAYKQYDDLQYYYSSZBYDSLNTFQTZQPZMCHDHCZCWFDXTMYQSPHQYYXSRGJCWTJTZZQMGWJJTJHTQJBBHWZPXXHYQFXXQYWYYHYSCDYDHHQMNMTMWCPBSZPPZZGLMZFOLLCFWHMMSJZTTDHZZYFFYTZZGZYSKYJXQYJZQBHMBZZLYGHGFMSHPZFZSNCLPBQSNJXZSLXXFPMTYJYGBXLLDLXPZJYZJYHHZCYWHJYLSJEXFSZZYWXKZJLUYDTMLYMQJPWXYHXSKTQJEZRPXXZHHMHWQPWQLYJJQJJZSZCPHJLCHHNXJLQWZJHBMZYXBDHHYPZLHLHLGFWLCHYYTLHJXCJMSCPXSTKPNHQXSRTYXXTESYJCTLSSLSTDLLLWWYHDHRJZSFGXTSYCZYNYHTDHWJSLHTZDQDJZXXQHGYLTZPHCSQFCLNJTCLZPFSTPDYNYLGMJLLYCQHYSSHCHYLHQYQTMZYPBYWRFQYKQSYSLZDQJMPXYYSSRHZJNYWTQDFZBWWTWWRXCWHGYHXMKMYYYQMSMZHNGCEPMLQQMTCWCTMMPXJPJJHFXYYZSXZHTYBMSTSYJTTQQQYYLHYNPYQZLCYZHZWSMYLKFJXLWGXYPJYTYSYXYMZCKTTWLKSMZSYLMPWLZWXWQZSSAQSYXYRHSSNTSRAPXCPWCMGDXHXZDZYFJHGZTTSBJHGYZSZYSMYCLLLXBTYXHBBZJKSSDMALXHYCFYGMQYPJYCQXJLLLJGSLZGQLYCJCCZOTYXMTMTTLLWTGPXYMZMKLPSZZZXHKQYSXCTYJZYHXSHYXZKXLZWPSQPYHJWPJPWXQQYLXSDHMRSLZZYZWTTCYXYSZZSHBSCCSTPLWSSCJCHNLCGCHSSPHYLHFHHXJSXYLLNYLSZDHZXYLSXLWZYKCLDYAXZCMDDYSPJTQJZLNWQPSSSWCTSTSZLBLNXSMNYYMJQBQHRZWTYYDCHQLXKPZWBGQYBKFCMZWPZLLYYLSZYDWHXPSBCMLJBSCGBHXLQHYRLJXYSWXWXZSLDFHLSLYNJLZYFLYJYCDRJLFSYZFSLLCQYQFGJYHYXZLYLMSTDJCYHBZLLNWLXXYGYYHSMGDHXXHHLZZJZXCZZZCYQZFNGWPYLCPKPYYPMCLQKDGXZGGWQBDXZZKZFBXXLZXJTPJPTTBYTSZZDWSLCHZHSLTYXHQLHYXXXYYZYSWTXZKHLXZXZPYHGCHKCFSYHUTJRLXFJXPTZTWHPLYXFCRHXSHXKYXXYHZQDXQWULHYHMJTBFLKHTXCWHJFWJCFPQRYQXCYYYQYGRPYWSGSUNGWCHKZDXYFLXXHJJBYZWTSXXNCYJJYMSWZJQRMHXZWFQSYLZJZGBHYNSLBGTTCSYBYXXWXYHXYYXNSQYXMQYWRGYQLXBBZLJSYLPSYTJZYHYZAWLRORJMKSCZJXXXYXCHDYXRYXXJDTSQFXLYLTSFFYXLMTYJMJUYYYXLTZCSXQZQHZXLYYXZHDNBRXXXJCTYHLBRLMBRLLAXKYLLLJLYXXLYCRYLCJTGJCMTLZLLCYZZPZPCYAWHJJFYBDYYZSMPCKZDQYQPBPCJPDCYZMDPBCYYDYCNNPLMTMLRMFMMGWYZBSJGYGSMZQQQZTXMKQWGXLLPJGZBQCDJJJFPKJKCXBLJMSWMDTQJXLDLPPBXCWRCQFBFQJCZAHZGMYKPHYYHZYKNDKZMBPJYXPXYHLFPNYYGXJDBKXNXHJMZJXSTRSTLDXSKZYSYBZXJLXYSLBZYSLHXJPFXPQNBYLLJQKYGZMCYZZYMCCSLCLHZFWFWYXZMWSXTYNXJHPYYMCYSPMHYSMYDYSHQYZCHMJJMZCAAGCFJBBHPLYZYLXXSDJGXDHKXXTXXNBHRMLYJSLTXMRHNLXQJXYZLLYSWQGDLBJHDCGJYQYCMHWFMJYBMBYJYJWYMDPWHXQLDYGPDFXXBCGJSPCKRSSYZJMSLBZZJFLJJJLGXZGYXYXLSZQYXBEXYXHGCXBPLDYHWETTWWCJMBTXCHXYQXLLXFLYXLLJLSSFWDPZSMYJCLMWYTCZPCHQEKCQBWLCQYDPLQPPQZQFJQDJHYMMCXTXDRMJWRHXCJZYLQXDYYNHYYHRSLSRSYWWZJYMTLTLLGTQCJZYABTCKZCJYCCQLJZQXALMZYHYWLWDXZXQDLLQSHGPJFJLJHJABCQZDJGTKHSSTCYJLPSWZLXZXRWGLDLZRLZXTGSLLLLZLYXXWGDZYGBDPHZPBRLWSXQBPFDWOFMWHLYPCBJCCLDMBZPBZZLCYQXLDOMZBLZWPDWYYGDSTTHCSQSCCRSSSYSLFYBFNTYJSZDFNDPDHDZZMBBLSLCMYFFGTJJQWFTMTPJWFNLBZCMMJTGBDZLQLPYFHYYMJYLSDCHDZJWJCCTLJCLDTLJJCPDDSQDSSZYBNDBJLGGJZXSXNLYCYBJXQYCBYLZCFZPPGKCXZDZFZTJJFJSJXZBNZYJQTTYJYHTYCZHYMDJXTTMPXSPLZCDWSLSHXYPZGTFMLCJTYCBPMGDKWYCYZCDSZZYHFLYCTYGWHKJYYLSJCXGYWJCBLLCSNDDBTZBSCLYZCZZSSQDLLMQYYHFSLQLLXFTYHABXGWNYWYYPLLSDLDLLBJCYXJZMLHLJDXYYQYTDLLLBUGBFDFBBQJZZMDPJHGCLGMJJPGAEHHBWCQXAXHHHZCHXYPHJAXHLPHJPGPZJQCQZGJJZZUZDMQYYBZZPHYHYBWHAZYJHYKFGDPFQSDLZMLJXKXGALXZDAGLMDGXMWZQYXXDXXPFDMMSSYMPFMDMMKXKSYZYSHDZKXSYSMMZZZMSYDNZZCZXFPLSTMZDNMXCKJMZTYYMZMZZMSXHHDCZJEMXXKLJSTLWLSQLYJZLLZJSSDPPMHNLZJCZYHMXXHGZCJMDHXTKGRMXFWMCGMWKDTKSXQMMMFZZYDKMSCLCMPCGMHSPXQPZDSSLCXKYXTWLWJYAHZJGZQMCSNXYYMMPMLKJXMHLMLQMXCTKZMJQYSZJSYSZHSYJZJCDAJZYBSDQJZGWZQQXFKDMSDJLFWEHKZQKJPEYPZYSZCDWYJFFMZZYLTTDZZEFMZLBNPPLPLPEPSZALLTYLKCKQZKGENQLWAGYXYDPXLHSXQQWQCQXQCLHYXXMLYCCWLYMQYSKGCHLCJNSZKPYZKCQZQLJPDMDZHLASXLBYDWQLWDNBQCRYDDZTJYBKBWSZDXDTNPJDTCTQDFXQQMGNXECLTTBKPWSLCTYQLPWYZZKLPYGZCQQPLLKCCYLPQMZCZQCLJSLQZDJXLDDHPZQDLJJXZQDXYZQKZLJCYQDYJPPYPQYKJYRMPCBYMCXKLLZLLFQPYLLLMBSGLCYSSLRSYSQTMXYXZQZFDZUYSYZTFFMZZSMZQHZSSCCMLYXWTPZGXZJGZGSJSGKDDHTQGGZLLBJDZLCBCHYXYZHZFYWXYZYMSDBZZYJGTSMTFXQYXQSTDGSLNXDLRYZZLRYYLXQHTXSRTZNGZXBNQQZFMYKMZJBZYMKBPNLYZPBLMCNQYZZZSJZHJCTZKHYZZJRDYZHNPXGLFZTLKGJTCTSSYLLGZRZBBQZZKLPKLCZYSSUYXBJFPNJZZXCDWXZYJXZZDJJKGGRSRJKMSMZJLSJYWQSKYHQJSXPJZZZLSNSHRNYPZTWCHKLPSRZLZXYJQXQKYSJYCZTLQZYBBYBWZPQDWWYZCYTJCJXCKCWDKKZXSGKDZXWWYYJQYYTCYTDLLXWKCZKKLCCLZCQQDZLQLCSFQCHQHSFSMQZZLNBJJZBSJHTSZDYSJQJPDLZCDCWJKJZZLPYCGMZWDJJBSJQZSYZYHHXJPBJYDSSXDZNCGLQMBTSFSBPDZDLZNFGFJGFSMPXJQLMBLGQCYYXBQKDJJQYRFKZTJDHCZKLBSDZCFJTPLLJGXHYXZCSSZZXSTJYGKGCKGYOQXJPLZPBPGTGYJZGHZQZZLBJLSQFZGKQQJZGYCZBZQTLDXRJXBSXXPZXHYZYCLWDXJJHXMFDZPFZHQHQMQGKSLYHTYCGFRZGNQXCLPDLBZCSCZQLLJBLHBZCYPZZPPDYMZZSGYHCKCPZJGSLJLNSCDSLDLXBMSTLDDFJMKDJDHZLZXLSZQPQPGJLLYBDSZGQLBZLSLKYYHZTTNTJYQTZZPSZQZTLLJTYYLLQLLQYZQLBDZLSLYYZYMDFSZSNHLXZNCZQZPBWSKRFBSYZMTHBLGJPMCZZLSTLXSHTCSYZLZBLFEQHLXFLCJLYLJQCBZLZJHHSSTBRMHXZHJZCLXFNBGXGTQJCZTMSFZKJMSSNXLJKBHSJXNTNLZDNTLMSJXGZJYJCZXYJYJWRWWQNZTNFJSZPZSHZJFYRDJSFSZJZBJFZQZZHZLXFYSBZQLZSGYFTZDCSZXZJBQMSZKJRHYJZCKMJKHCHGTXKXQGLXPXFXTRTYLXJXHDTSJXHJZJXZWZLCQSBTXWXGXTXXHXFTSDKFJHZYJFJXRZSDLLLTQSQQZQWZXSYQTWGWBZCGZLLYZBCLMQQTZHZXZXLJFRMYZFLXYSQXXJKXRMQDZDMMYYBSQBHGZMWFWXGMXLZPYYTGZYCCDXYZXYWGSYJYZNBHPZJSQSYXSXRTFYZGRHZTXSZZTHCBFCLSYXZLZQMZLMPLMXZJXSFLBYZMYQHXJSXRXSQZZZSSLYFRCZJRCRXHHZXQYDYHXSJJHZCXZBTYNSYSXJBQLPXZQPYMLXZKYXLXCJLCYSXXZZLXDLLLJJYHZXGYJWKJRWYHCPSGNRZLFZWFZZNSXGXFLZSXZZZBFCSYJDBRJKRDHHGXJLJJTGXJXXSTJTJXLYXQFCSGSWMSBCTLQZZWLZZKXJMLTMJYHSDDBXGZHDLBMYJFRZFSGCLYJBPMLYSMSXLSZJQQHJZFXGFQFQBPXZGYYQXGZTCQWYLTLGWSGWHRLFSFGZJMGMGBGTJFSYZZGZYZAFLSSPMLPFLCWBJZCLJJMZLPJJLYMQDMYYYFBGYGYZMLYZDXQYXRQQQHSYYYQXYLJTYXFSFSLLGNQCYHYCWFHCCCFXPYLYPLLZYXXXXXKQHHXSHJZCFZSCZJXCPZWHHHHHAPYLQALPQAFYHXDYLUKMZQGGGDDESRNNZLTZGCHYPPYSQJJHCLLJTOLNJPZLJLHYMHEYDYDSQYCDDHGZUNDZCLZYZLLZNTNYZGSLHSLPJJBDGWXPCDUTJCKLKCLWKLLCASSTKZZDNQNTTLYYZSSYSSZZRYLJQKCQDHHCRXRZYDGRGCWCGZQFFFPPJFZYNAKRGYWYQPQXXFKJTSZZXSWZDDFBBXTBGTZKZNPZZPZXZPJSZBMQHKCYXYLDKLJNYPKYGHGDZJXXEAHPNZKZTZCMXCXMMJXNKSZQNMNLWBWWXJKYHCPSTMCSQTZJYXTPCTPDTNNPGLLLZSJLSPBLPLQHDTNJNLYYRSZFFJFQWDPHZDWMRZCCLODAXNSSNYZRESTYJWJYJDBCFXNMWTTBYLWSTSZGYBLJPXGLBOCLHPCBJLTMXZLJYLZXCLTPNCLCKXTPZJSWCYXSFYSZDKNTLBYJCYJLLSTGQCBXRYZXBXKLYLHZLQZLNZCXWJZLJZJNCJHXMNZZGJZZXTZJXYCYYCXXJYYXJJXSSSJSTSSTTPPGQTCSXWZDCSYFPTFBFHFBBLZJCLZZDBXGCXLQPXKFZFLSYLTUWBMQJHSZBMDDBCYSCCLDXYCDDQLYJJWMQLLCSGLJJSYFPYYCCYLTJANTJJPWYCMMGQYYSXDXQMZHSZXPFTWWZQSWQRFKJLZJQQYFBRXJHHFWJJZYQAZMYFRHCYYBYQWLPEXCCZSTYRLTTDMQLYKMBBGMYYJPRKZNPBSXYXBHYZDJDNGHPMFSGMWFZMFQMMBCMZZCJJLCNUXYQLMLRYGQZCYXZLWJGCJCGGMCJNFYZZJHYCPRRCMTZQZXHFQGTJXCCJEAQCRJYHPLQLSZDJRBCQHQDYRHYLYXJSYMHZYDWLDFRYHBPYDTSSCNWBXGLPZMLZZTQSSCPJMXXYCSJYTYCGHYCJWYRXXLFEMWJNMKLLSWTXHYYYNCMMCWJDQDJZGLLJWJRKHPZGGFLCCSCZMCBLTBHBQJXQDSPDJZZGKGLFQYWBZYZJLTSTDHQHCTCBCHFLQMPWDSHYYTQWCNZZJTLBYMBPDYYYXSQKXWYYFLXXNCWCXYPMAELYKKJMZZZBRXYYQJFLJPFHHHYTZZXSGQQMHSPGDZQWBWPJHZJDYSCQWZKTXXSQLZYYMYSDZGRXCKKUJLWPYSYSCSYZLRMLQSYLJXBCXTLWDQZPCYCYKPPPNSXFYZJJRCEMHSZMSXLXGLRWGCSTLRSXBZGBZGZTCPLUJLSLYLYMTXMTZPALZXPXJTJWTCYYZLBLXBZLQMYLXPGHDSLSSDMXMBDZZSXWHAMLCZCPJMCNHJYSNSYGCHSKQMZZQDLLKABLWJXSFMOCDXJRRLYQZKJMYBYQLYHETFJZFRFKSRYXFJTWDSXXSYSQJYSLYXWJHSNLXYYXHBHAWHHJZXWMYLJCSSLKYDZTXBZSYFDXGXZJKHSXXYBSSXDPYNZWRPTQZCZENYGCXQFJYKJBZMLJCMQQXUOXSLYXXLYLLJDZBTYMHPFSTTQQWLHOKYBLZZALZXQLHZWRRQHLSTMYPYXJJXMQSJFNBXYXYJXXYQYLTHYLQYFMLKLJTMLLHSZWKZHLJMLHLJKLJSTLQXYLMBHHLNLZXQJHXCFXXLHYHJJGBYZZKBXSCQDJQDSUJZYYHZHHMGSXCSYMXFEBCQWWRBPYYJQTYZCYQYQQZYHMWFFHGZFRJFCDPXNTQYZPDYKHJLFRZXPPXZDBBGZQSTLGDGYLCQMLCHHMFYWLZYXKJLYPQHSYWMQQGQZMLZJNSQXJQSYJYCBEHSXFSZPXZWFLLBCYYJDYTDTHWZSFJMQQYJLMQXXLLDTTKHHYBFPWTYYSQQWNQWLGWDEBZWCMYGCULKJXTMXMYJSXHYBRWFYMWFRXYQMXYSZTZZTFYKMLDHQDXWYYNLCRYJBLPSXCXYWLSPRRJWXHQYPHTYDNXHHMMYWYTZCSQMTSSCCDALWZTCPQPYJLLQZYJSWXMZZMMYLMXCLMXCZMXMZSQTZPPQQBLPGXQZHFLJJHYTJSRXWZXSCCDLXTYJDCQJXSLQYCLZXLZZXMXQRJMHRHZJBHMFLJLMLCLQNLDXZLLLPYPSYJYSXCQQDCMQJZZXHNPNXZMEKMXHYKYQLXSXTXJYYHWDCWDZHQYYBGYBCYSCFGPSJNZDYZZJZXRZRQJJYMCANYRJTLDPPYZBSTJKXXZYPFDWFGZZRPYMTNGXZQBYXNBUFNQKRJQZMJEGRZGYCLKXZDSKKNSXKCLJSPJYYZLQQJYBZSSQLLLKJXTBKTYLCCDDBLSPPFYLGYDTZJYQGGKQTTFZXBDKTYYHYBBFYTYYBCLPDYTGDHRYRNJSPTCSNYJQHKLLLZSLYDXXWBCJQSPXBPJZJCJDZFFXXBRMLAZHCSNDLBJDSZBLPRZTSWSBXBCLLXXLZDJZSJPYLYXXYFTFFFBHJJXGBYXJPMMMPSSJZJMTLYZJXSWXTYLEDQPJMYGQZJGDJLQJWJQLLSJGJGYGMSCLJJXDTYGJQJQJCJZCJGDZZSXQGSJGGCXHQXSNQLZZBXHSGZXCXYLJXYXYYDFQQJHJFXDHCTXJYRXYSQTJXYEFYYSSYYJXNCYZXFXMSYSZXYYSCHSHXZZZGZZZGFJDLTYLNPZGYJYZYYQZPBXQBDZTZCZYXXYHHSQXSHDHGQHJHGYWSZTMZMLHYXGEBTYLZKQWYTJZRCLEKYSTDBCYKQQSAYXCJXWWGSBHJYZYDHCSJKQCXSWXFLTYNYZPZCCZJQTZWJQDZZZQZLJJXLSBHPYXXPSXSHHEZTXFPTLQYZZXHYTXNCFZYYHXGNXMYWXTZSJPTHHGYMXMXQZXTSBCZYJYXXTYYZYPCQLMMSZMJZZLLZXGXZAAJZYXJMZXWDXZSXZDZXLEYJJZQBHZWZZZQTZPSXZTDSXJJJZNYAZPHXYYSRNQDTHZHYYKYJHDZXZLSWCLYBZYECWCYCRYLCXNHZYDZYDYJDFRJJHTRSQTXYXJRJHOJYNXELXSFSFJZGHPZSXZSZDZCQZBYYKLSGSJHCZSHDGQGXYZGXCHXZJWYQWGYHKSSEQZZNDZFKWYSSTCLZSTSYMCDHJXXYWEYXCZAYDMPXMDSXYBSQMJMZJMTZQLPJYQZCGQHXJHHLXXHLHDLDJQCLDWBSXFZZYYSCHTYTYYBHECXHYKGJPXHHYZJFXHWHBDZFYZBCAPNPGNYDMSXHMMMMAMYNBYJTMPXYYMCTHJBZYFCGTYHWPHFTWZZEZSBZEGPFMTSKFTYCMHFLLHGPZJXZJGZJYXZSBBQSCZZLZCCSTPGXMJSFTCCZJZDJXCYBZLFCJSYZFGSZLYBCWZZBYZDZYPSWYJZXZBDSYUXLZZBZFYGCZXBZHZFTPBGZGEJBSTGKDMFHYZZJHZLLZZGJQZLSFDJSSCBZGPDLFZFZSZYZYZSYGCXSNXXCHCZXTZZLJFZGQSQYXZJQDCCZTQCDXZJYQJQCHXZTDLGSCXZSYQJQTZWLQDQZTQCHQQJZYEZZZPBWKDJFCJPZTYPQYQTTYNLMBDKTJZPQZQZZFPZSBNJLGYJDXJDZZKZGQKXDLPZJTCJDQBXDJQJSTCKNXBXZMSLYJCQMTJQWWCJQNJNLLLHJCWQTBZQYDZCZPZZDZYDDCYZZZCCJTTJFZDPRRTZTJDCQTQZDTJNPLZBCLLCTZSXKJZQZPZLBZRBTJDCXFCZDBCCJJLTQQPLDCGZDBBZJCQDCJWYNLLZYZCCDWLLXWZLXRXNTQQCZXKQLSGDFQTDDGLRLAJJTKUYMKQLLTZYTDYYCZGJWYXDXFRSKSTQTENQMRKQZHHQKDLDAZFKYPBGGPZREBZZYKZZSPEGJXGYKQZZZSLYSYYYZWFQZYLZZLZHWCHKYPQGNPGBLPLRRJYXCCSYYHSFZFYBZYYTGZXYLXCZWXXZJZBLFFLGSKHYJZEYJHLPLLLLCZGXDRZELRHGKLZZYHZLYQSZZJZQLJZFLNBHGWLCZCFJYSPYXZLZLXGCCPZBLLCYBBBBUBBCBPCRNNZCZYRBFSRLDCGQYYQXYGMQZWTZYTYJXYFWTEHZZJYWLCCNTZYJJZDEDPZDZTSYQJHDYMBJNYJZLXTSSTPHNDJXXBYXQTZQDDTJTDYYTGWSCSZQFLSHLGLBCZPHDLYZJYCKWTYTYLBNYTSDSYCCTYSZYYEBHEXHQDTWNYGYCLXTSZYSTQMYGZAZCCSZZDSLZCLZRQXYYELJSBYMXSXZTEMBBLLYYLLYTDQYSHYMRQWKFKBFXNXSBYCHXBWJYHTQBPBSBWDZYLKGZSKYHXQZJXHXJXGNLJKZLYYCDXLFYFGHLJGJYBXQLYBXQPQGZTZPLNCYPXDJYQYDYMRBESJYYHKXXSTMXRCZZYWXYQYBMCLLYZHQYZWQXDBXBZWZMSLPDMYSKFMZKLZCYQYCZLQXFZZYDQZPZYGYJYZMZXDZFYFYTTQTZHGSPCZMLCCYTZXJCYTJMKSLPZHYSNZLLYTPZCTZZCKTXDHXXTQCYFKSMQCCYYAZHTJPCYLZLYJBJXTPNYLJYYNRXSYLMMNXJSMYBCSYSYLZYLXJJQYLDZLPQBFZZBLFNDXQKCZFYWHGQMRDSXYCYTXNQQJZYYPFZXDYZFPRXEJDGYQBXRCNFYYQPGHYJDYZXGRHTKYLNWDZNTSMPKLBTHBPYSZBZTJZSZZJTYYXZPHSSZZBZCZPTQFZMYFLYPYBBJQXZMXXDJMTSYSKKBJZXHJCKLPSMKYJZCXTMLJYXRZZQSLXXQPYZXMKYXXXJCLJPRMYYGADYSKQLSNDHYZKQXZYZTCGHZTLMLWZYBWSYCTBHJHJFCWZTXWYTKZLXQSHLYJZJXTMPLPYCGLTBZZTLZJCYJGDTCLKLPLLQPJMZPAPXYZLKKTKDZCZZBNZDYDYQZJYJGMCTXLTGXSZLMLHBGLKFWNWZHDXUHLFMKYSLGXDTWWFRJEJZTZHYDXYKSHWFZCQSHKTMQQHTZHYMJDJSKHXZJZBZZXYMPAGQMSTPXLSKLZYNWRTSQLSZBPSPSGZWYHTLKSSSWHZZLYYTNXJGMJSZSUFWNLSOZTXGXLSAMMLBWLDSZYLAKQCQCTMYCFJBSLXCLZZCLXXKSBZQCLHJPSQPLSXXCKSLNHPSFQQYTXYJZLQLDXZQJZDYYDJNZPTUZDSKJFSLJHYLZSQZLBTXYDGTQFDBYAZXDZHZJNHHQBYKNXJJQCZMLLJZKSPLDYCLBBLXKLELXJLBQYCXJXGCNLCQPLZLZYJTZLJGYZDZPLTQCSXFDMNYCXGBTJDCZNBGBQYQJWGKFHTNPYQZQGBKPBBYZMTJDYTBLSQMPSXTBNPDXKLEMYYCJYNZCTLDYKZZXDDXHQSHDGMZSJYCCTAYRZLPYLTLKXSLZCGGEXCLFXLKJRTLQJAQZNCMBYDKKCXGLCZJZXJHPTDJJMZQYKQSECQZDSHHADMLZFMMZBGNTJNNLGBYJBRBTMLBYJDZXLCJLPLDLPCQDHLXZLYCBLCXZZJADJLNZMMSSSMYBHBSQKBHRSXXJMXSDZNZPXLGBRHWGGFCXGMSKLLTSJYYCQLTSKYWYYHYWXBXQYWPYWYKQLSQPTNTKHQCWDQKTWPXXHCPTHTWUMSSYHBWCRWXHJMKMZNGWTMLKFGHKJYLSYYCXWHYECLQHKQHTTQKHFZLDXQWYZYYDESBPKYRZPJFYYZJCEQDZZDLATZBBFJLLCXDLMJSSXEGYGSJQXCWBXSSZPDYZCXDNYXPPZYDLYJCZPLTXLSXYZYRXCYYYDYLWWNZSAHJSYQYHGYWWAXTJZDAXYSRLTDPSSYYFNEJDXYZHLXLLLZQZSJNYQYQQXYJGHZGZCYJCHZLYCDSHWSHJZYJXCLLNXZJJYYXNFXMWFPYLCYLLABWDDHWDXJMCXZTZPMLQZHSFHZYNZTLLDYWLSLXHYMMYLMBWWKYXYADTXYLLDJPYBPWUXJMWMLLSAFDLLYFLBHHHBQQLTZJCQJLDJTFFKMMMBYTHYGDCQRDDWRQJXNBYSNWZDBYYTBJHPYBYTTJXAAHGQDQTMYSTQXKBTZPKJLZRBEQQSSMJJBDJOTGTBXPGBKTLHQXJJJCTHXQDWJLWRFWQGWSHCKRYSWGFTGYGBXSDWDWRFHWYTJJXXXJYZYSLPYYYPAYXHYDQKXSHXYXGSKQHYWFDDDPPLCJLQQEEWXKSYYKDYPLTJTHKJLTCYYHHJTTPLTZZCDLTHQKZXQYSTEEYWYYZYXXYYSTTJKLLPZMCYHQGXYHSRMBXPLLNQYDQHXSXXWGDQBSHYLLPJJJTHYJKYPPTHYYKTYEZYENMDSHLCRPQFDGFXZPSFTLJXXJBSWYYSKSFLXLPPLBBBLBSFXFYZBSJSSYLPBBFFFFSSCJDSTZSXZRYYSYFFSYZYZBJTBCTSBSDHRTJJBYTCXYJEYLXCBNEBJDSYXYKGSJZBXBYTFZWGENYHHTHZHHXFWGCSTBGXKLSXYWMTMBYXJSTZSCDYQRCYTWXZFHMYMCXLZNSDJTTTXRYCFYJSBSDYERXJLJXBBDEYNJGHXGCKGSCYMBLXJMSZNSKGXFBNBPTHFJAAFXYXFPXMYPQDTZCXZZPXRSYWZDLYBBKTYQPQJPZYPZJZNJPZJLZZFYSBTTSLMPTZRTDXQSJEHBZYLZDHLJSQMLHTXTJECXSLZZSPKTLZKQQYFSYGYWPCPQFHQHYTQXZKRSGTTSQCZLPTXCDYYZXSQZSLXLZMYCPCQBZYXHBSXLZDLTCDXTYLZJYYZPZYZLTXJSJXHLPMYTXCQRBLZSSFJZZTNJYTXMYJHLHPPLCYXQJQQKZZSCPZKSWALQSBLCCZJSXGWWWYGYKTJBBZTDKHXHKGTGPBKQYSLPXPJCKBMLLXDZSTBKLGGQKQLSBKKTFXRMDKBFTPZFRTBBRFERQGXYJPZSSTLBZTPSZQZSJDHLJQLZBPMSMMSXLQQNHKNBLRDDNXXDHDDJCYYGYLXGZLXSYGMQQGKHBPMXYXLYTQWLWGCPBMQXCYZYDRJBHTDJYHQSHTMJSBYPLWHLZFFNYPMHXXHPLTBQPFBJWQDBYGPNZTPFZJGSDDTQSHZEAWZZYLLTYYBWJKXXGHLFKXDJTMSZSQYNZGGSWQSPHTLSSKMCLZXYSZQZXNCJDQGZDLFNYKLJCJLLZLMZZNHYDSSHTHZZLZZBBHQZWWYCRZHLYQQJBEYFXXXWHSRXWQHWPSLMSSKZTTYGYQQWRSLALHMJTQJSMXQBJJZJXZYZKXBYQXBJXSHZTSFJLXMXZXFGHKZSZGGYLCLSARJYHSLLLMZXELGLXYDJYTLFBHBPNLYZFBBHPTGJKWETZHKJJXZXXGLLJLSTGSHJJYQLQZFKCGNNDJSSZFDBCTWWSEQFHQJBSAQTGYPQLBXBMMYWXGSLZHGLZGQYFLZBYFZJFRYSFMBYZHQGFWZSYFYJJPHZBYYZFFWODGRLMFTWLBZGYCQXCDJYGZYYYYTYTYDWEGAZYHXJLZYYHLRMGRXXZCLHNELJJTJTPWJYBJJBXJJTJTEEKHWSLJPLPSFYZPQQBDLQJJTYYQLYZKDKSQJYYQZLDQTGJQYZJSUCMRYQTHTEJMFCTYHYPKMHYZWJDQFHYYXWSHCTXRLJHQXHCCYYYJLTKTTYTMXGTCJTZAYYOCZLYLBSZYWJYTSJYHBYSHFJLYGJXXTMZYYLTXXYPZLXYJZYZYYPNHMYMDYYLBLHLSYYQQLLNJJYMSOYQBZGDLYXYLCQYXTSZEGXHZGLHWBLJHEYXTWQMAKBPQCGYSHHEGQCMWYYWLJYJHYYZLLJJYLHZYHMGSLJLJXCJJYCLYCJPCPZJZJMMYLCQLNQLJQJSXYJMLSZLJQLYCMMHCFMMFPQQMFYLQMCFFQMMMMHMZNFHHJGTTHHKHSLNCHHYQDXTMMQDCYZYXYQMYQYLTDCYYYZAZZCYMZYDLZFFFMMYCQZWZZMABTBYZTDMNZZGGDFTYPCGQYTTSSFFWFDTZQSSYSTWXJHXYTSXXYLBYQHWWKXHZXWZNNZZJZJJQJCCCHYYXBZXZCYZTLLCQXYNJYCYYCYNZZQYYYEWYCZDCJYCCHYJLBTZYYCQWMPWPYMLGKDLDLGKQQBGYCHJXY";
//此处收录了375个多音字,数据来自于http://www.51window.net/page/pinyin
var oMultiDiff={"19969":"DZ","19975":"WM","19988":"QJ","20048":"YL","20056":"SC","20060":"NM","20094":"QG","20127":"QJ","20167":"QC","20193":"YG","20250":"KH","20256":"ZC","20282":"SC","20285":"QJG","20291":"TD","20314":"YD","20340":"NE","20375":"TD","20389":"YJ","20391":"CZ","20415":"PB","20446":"YS","20447":"SQ","20504":"TC","20608":"KG","20854":"QJ","20857":"ZC","20911":"PF","20504":"TC","20608":"KG","20854":"QJ","20857":"ZC","20911":"PF","20985":"AW","21032":"PB","21048":"XQ","21049":"SC","21089":"YS","21119":"JC","21242":"SB","21273":"SC","21305":"YP","21306":"QO","21330":"ZC","21333":"SDC","21345":"QK","21378":"CA","21397":"SC","21414":"XS","21442":"SC","21477":"JG","21480":"TD","21484":"ZS","21494":"YX","21505":"YX","21512":"HG","21523":"XH","21537":"PB","21542":"PF","21549":"KH","21571":"E","21574":"DA","21588":"TD","21589":"O","21618":"ZC","21621":"KHA","21632":"ZJ","21654":"KG","21679":"LKG","21683":"KH","21710":"A","21719":"YH","21734":"WOE","21769":"A","21780":"WN","21804":"XH","21834":"A","21899":"ZD","21903":"RN","21908":"WO","21939":"ZC","21956":"SA","21964":"YA","21970":"TD","22003":"A","22031":"JG","22040":"XS","22060":"ZC","22066":"ZC","22079":"MH","22129":"XJ","22179":"XA","22237":"NJ","22244":"TD","22280":"JQ","22300":"YH","22313":"XW","22331":"YQ","22343":"YJ","22351":"PH","22395":"DC","22412":"TD","22484":"PB","22500":"PB","22534":"ZD","22549":"DH","22561":"PB","22612":"TD","22771":"KQ","22831":"HB","22841":"JG","22855":"QJ","22865":"XQ","23013":"ML","23081":"WM","23487":"SX","23558":"QJ","23561":"YW","23586":"YW","23614":"YW","23615":"SN","23631":"PB","23646":"ZS","23663":"ZT","23673":"YG","23762":"TD","23769":"ZS","23780":"QJ","23884":"QK","24055":"XH","24113":"DC","24162":"ZC","24191":"GA","24273":"QJ","24324":"NL","24377":"TD","24378":"QJ","24439":"PF","24554":"ZS","24683":"TD","24694":"WE","24733":"LK","24925":"TN","25094":"ZG","25100":"XQ","25103":"XH","25153":"PB","25170":"PB","25179":"KG","25203":"PB","25240":"ZS","25282":"FB","25303":"NA","25324":"KG","25341":"ZY","25373":"WZ","25375":"XJ","25384":"A","25457":"A","25528":"SD","25530":"SC","25552":"TD","25774":"ZC","25874":"ZC","26044":"YW","26080":"WM","26292":"PB","26333":"PB","26355":"ZY","26366":"CZ","26397":"ZC","26399":"QJ","26415":"ZS","26451":"SB","26526":"ZC","26552":"JG","26561":"TD","26588":"JG","26597":"CZ","26629":"ZS","26638":"YL","26646":"XQ","26653":"KG","26657":"XJ","26727":"HG","26894":"ZC","26937":"ZS","26946":"ZC","26999":"KJ","27099":"KJ","27449":"YQ","27481":"XS","27542":"ZS","27663":"ZS","27748":"TS","27784":"SC","27788":"ZD","27795":"TD","27812":"O","27850":"PB","27852":"MB","27895":"SL","27898":"PL","27973":"QJ","27981":"KH","27986":"HX","27994":"XJ","28044":"YC","28065":"WG","28177":"SM","28267":"QJ","28291":"KH","28337":"ZQ","28463":"TL","28548":"DC","28601":"TD","28689":"PB","28805":"JG","28820":"QG","28846":"PB","28952":"TD","28975":"ZC","29100":"A","29325":"QJ","29575":"SL","29602":"FB","30010":"TD","30044":"CX","30058":"PF","30091":"YSP","30111":"YN","30229":"XJ","30427":"SC","30465":"SX","30631":"YQ","30655":"QJ","30684":"QJG","30707":"SD","30729":"XH","30796":"LG","30917":"PB","31074":"NM","31085":"JZ","31109":"SC","31181":"ZC","31192":"MLB","31293":"JQ","31400":"YX","31584":"YJ","31896":"ZN","31909":"ZY","31995":"XJ","32321":"PF","32327":"ZY","32418":"HG","32420":"XQ","32421":"HG","32438":"LG","32473":"GJ","32488":"TD","32521":"QJ","32527":"PB","32562":"ZSQ","32564":"JZ","32735":"ZD","32793":"PB","33071":"PF","33098":"XL","33100":"YA","33152":"PB","33261":"CX","33324":"BP","33333":"TD","33406":"YA","33426":"WM","33432":"PB","33445":"JG","33486":"ZN","33493":"TS","33507":"QJ","33540":"QJ","33544":"ZC","33564":"XQ","33617":"YT","33632":"QJ","33636":"XH","33637":"YX","33694":"WG","33705":"PF","33728":"YW","33882":"SR","34067":"WM","34074":"YW","34121":"QJ","34255":"ZC","34259":"XL","34425":"JH","34430":"XH","34485":"KH","34503":"YS","34532":"HG","34552":"XS","34558":"YE","34593":"ZL","34660":"YQ","34892":"XH","34928":"SC","34999":"QJ","35048":"PB","35059":"SC","35098":"ZC","35203":"TQ","35265":"JX","35299":"JX","35782":"SZ","35828":"YS","35830":"E","35843":"TD","35895":"YG","35977":"MH","36158":"JG","36228":"QJ","36426":"XQ","36466":"DC","36710":"JC","36711":"ZYG","36767":"PB","36866":"SK","36951":"YW","37034":"YX","37063":"XH","37218":"ZC","37325":"ZC","38063":"PB","38079":"TD","38085":"QY","38107":"DC","38116":"TD","38123":"YD","38224":"HG","38241":"XTC","38271":"ZC","38415":"YE","38426":"KH","38461":"YD","38463":"AE","38466":"PB","38477":"XJ","38518":"YT","38551":"WK","38585":"ZC","38704":"XS","38739":"LJ","38761":"GJ","38808":"SQ","39048":"JG","39049":"XJ","39052":"HG","39076":"CZ","39271":"XT","39534":"TD","39552":"TD","39584":"PB","39647":"SB","39730":"LG","39748":"TPB","40109":"ZQ","40479":"ND","40516":"HG","40536":"HG","40583":"QJ","40765":"YQ","40784":"QJ","40840":"YK","40863":"QJG"};
//参数,中文字符串  
//返回值:拼音首字母串数组  
function makePy(str){
  if(typeof(str) != "string")
      throw new Error(-1,"函数makePy需要字符串类型参数!");
  var arrResult = new Array(); //保存中间结果的数组
  for(var i=0,len=str.length;i<len;i++){
      //获得unicode码
      var ch = str.charAt(i);
      //检查该unicode码是否在处理范围之内,在则返回该码对映汉字的拼音首字母,不在则调用其它函数处理
      arrResult.push(checkCh(ch));
  }
  //处理arrResult,返回所有可能的拼音首字母串数组
  return mkRslt(arrResult);
}
function checkCh(ch){
  var uni = ch.charCodeAt(0);
  //如果不在汉字处理范围之内,返回原字符,也可以调用自己的处理函数
  if(uni > 40869 || uni < 19968)
      return ch; //dealWithOthers(ch);
  //检查是否是多音字,是按多音字处理,不是就直接在strChineseFirstPY字符串中找对应的首字母
  return (strChineseFirstPY.charAt(uni-19968));
}
function mkRslt(arr){
  var arrRslt = [""];
  for(var i=0,len=arr.length;i<len;i++){
      var str = arr[i];
      var strlen = str.length;
      if(strlen == 1){
          for(var k=0;k<arrRslt.length;k++){
              arrRslt[k] += str;
          }
      }else{
          var tmpArr = arrRslt.slice(0);
          arrRslt = [];
          for(k=0;k<strlen;k++){
              //复制一个相同的arrRslt
              var tmp = tmpArr.slice(0);
              //把当前字符str[k]添加到每个元素末尾
              for(var j=0;j<tmp.length;j++){
                  tmp[j] += str.charAt(k);
              }
              //把复制并修改后的数组连接到arrRslt上
              arrRslt = arrRslt.concat(tmp);
          }
      }
  }
  // 去除前后空格
  //arrRslt = arrRslt.toString().replace(/(^\s*)|(\s*$)/g,"");
  // 去除所有空格
  arrRslt = arrRslt.toString().replace(/\s+/g,"");
  return arrRslt;
}
</script>
    <ul id="myTab1" class="nav nav-tabs">
        <c:if  test="${fn:contains(sessionScope.pd.purview_map,'zdrxx')==true}">
        <li  class="active">
            <a href="#icbc_zdr" data-toggle="tab">主贷人信息</a>
        </li>
        </c:if>
        <c:if  test="${fn:contains(sessionScope.pd.purview_map,'ghrxx')==true}">
        <li >
            <a href="#ghr" data-toggle="tab">共还人信息</a>
        </li>
        </c:if>
        <c:if  test="${fn:contains(sessionScope.pd.purview_map,'qtlxr')==true}">
         <li>
            <a href="#qtlxr" data-toggle="tab">紧急联系人</a>
        </li>
        </c:if>
        <c:if  test="${fn:contains(sessionScope.pd.purview_map,'srxx')==true}">
         <li>
            <a href="#srxx" data-toggle="tab">收入信息 </a>
        </li>
        </c:if>
        <c:if  test="${fn:contains(sessionScope.pd.purview_map,'jtxx')==true}">
         <li>
            <a href="#jtxx" data-toggle="tab">家庭信息</a>
        </li>
        </c:if>
        <c:if  test="${fn:contains(sessionScope.pd.purview_map,'fcxx')==true}">
         <li>
            <a href="#fcxx" data-toggle="tab">房产信息</a>
        </li>
       </c:if>
    </ul>
    <div id="myTab1Content" class="tab-content">
    
<div id="icbc_zdr" class="tab-pane fade active in">
    <form name="modalForm" class="form-horizontal">
    <div style="border:1px solid #478FCA;   margin:5px; padding:20px;border-radius: 10px;">
   <div class="form-group">
		 <label class="col-sm-2 control-label">姓名<i class="red">*</i></label>
			<div class="col-sm-3">
			<input name="c_name" id="c_name" class="form-control"  value="${pd.c_name }" type="text">
			</div>
			    <label class="col-sm-2 control-label">拼音<i class="red">*</i></label>
			<div class="col-sm-3">
			<input name="englishname" id="englishname" class="form-control"  value="" type="text">
			</div>
	</div>		
		   <div class="form-group">
		 <label class="col-sm-2 control-label">出生日期<i class="red">*</i></label>
			<div class="col-sm-3">
			<input name="birthday" id="birthday" class="form-control"  value="" type="text">
			</div>
			    <label class="col-sm-2 control-label">身份证号<i class="red">*</i></label>
			<div class="col-sm-3">
			<input name="c_cardno" id="c_cardno" class="form-control"  value="${pd.c_cardno }" type="text">
			</div>
	      </div>		
		   <div class="form-group">
			<label class="col-sm-2 control-label">性别<i class="red">*</i></label>
			<div class="col-sm-8">
			<select class="form-control" id="c_sex" name="c_sex">
			<option value="2">请选择</option>
			<option value="1" ${pd.c_sex eq '1'?"selected='selected'":''}>男</option>
			<option value="0" ${pd.c_sex eq '0'?"selected='selected'":''}>女</option>
			</select>
			</div>
			<!-- <label class="col-sm-2 control-label">民族<i class="red">*</i></label>
			<div class="col-sm-3">
			<input  name="" id="" class="form-control"  value="汉" type="hidden">
			</div> -->
	      </div>
		  <!-- <div class="form-group">
		 	<label class="col-sm-2 control-label">户籍地址<i class="red">*</i></label>
			<div class="col-sm-3">
			<input name="" id="" class="form-control"  value="上海市黄浦区半淞园路松原大厦A单元501室" type="text">
			</div>
			    <label class="col-sm-2 control-label">签证机关<i class="red">*</i></label>
			<div class="col-sm-3">
			<input name="" id="" class="form-control"  value="福州市鼓楼区公安局" type="text">
			</div>
	      </div> -->
		  <!--  <div class="form-group">
		  <label class="col-sm-2 control-label">有效期限开始<i class="red">*</i></label>
			<div class="col-sm-3">
			<input name="" id="" class="form-control"  value="2010-01-01" type="text">
			</div>
			    <label class="col-sm-2 control-label">有效期限结束<i class="red">*</i></label>
			<div class="col-sm-3">
			<input name="" id="" class="form-control"  value="2019-01-01" type="text">
			</div>
	      </div> -->
		   <div class="form-group">
		 <label class="col-sm-2 control-label">业务员姓名<i class="red">*</i></label>
			<div class="col-sm-3">
			<input name="gemsname" id="gemsname" class="form-control"  value="${pd.gemsname }" type="text">
			</div>
			    <label class="col-sm-2 control-label">所属机构<i class="red">*</i></label>
			<div class="col-sm-3">
			<input name="fsname" id="fsname" class="form-control"  value="${pd.fsname }" type="text">
			</div>
	      </div>
		   <div class="form-group">
		 <label class="col-sm-2 control-label">手机号码<i class="red">*</i></label>
			<div class="col-sm-3">
			<input name="c_tel" id="c_tel" class="form-control"  value="${pd.c_tel }" type="text">
			</div>
			    <label class="col-sm-2 control-label">婚姻状况<i class="red">*</i></label>
			<div class="col-sm-3">
						<select id="zdr_hyzk" name="zdr_hyzk" onchange="autopo();" class="form-control" tabindex="-1" >
								<option value="-1">请选择</option>
								<option value="0" ${pd.zdr_hyzk eq '0'?"selected='selected'":''}>未婚</option>
								<option value="1" ${pd.zdr_hyzk eq '1'?"selected='selected'":''} >已婚</option>
								<option value="2" ${pd.zdr_hyzk eq '2'?"selected='selected'":''}>离异</option>
								<option value="3"  ${pd.zdr_hyzk eq '3'?"selected='selected'":''}>丧偶</option>							</select>
			</div>
			</div>
          <div class="form-group">
		 <label class="col-sm-2 control-label">有无子女<i class="red">*</i></label>
			<div class="col-sm-3">
			<input name="" id="" class="form-control"  value="无" type="text">
			</div>
			    <label class="col-sm-2 control-label">赌博记录<i class="red">*</i></label>
			<div class="col-sm-3">
		      <input class="form-control"  id="" name="" value="无" type="text"  />    
				</div>
			</div>
          <div class="form-group">
		 <label class="col-sm-2 control-label">法院经济案<i class="red">*</i></label>
			<div class="col-sm-3">
			<input name="" id="" class="form-control"  value="无" type="text">
			</div>
			    <label class="col-sm-2 control-label">最高学历<i class="red">*</i></label>
			<div class="col-sm-3">
		     <select id="zdr_xl" name="zdr_xl" class="form-control" tabindex="-1">
								<option value="0" >请选择</option>
								<option value="1" ${pd.zdr_xl eq '1'?"selected='selected'":''}>小学</option>
								<option value="2" ${pd.zdr_xl eq '2'?"selected='selected'":''}>初中</option>
								<option value="3" ${pd.zdr_xl eq '3'?"selected='selected'":''}>高中</option>
								<option value="4" ${pd.zdr_xl eq '4'?"selected='selected'":''}>大专</option>
								<option value="5" ${pd.zdr_xl eq '5'?"selected='selected'":''}>本科</option>
								<option value="6" ${pd.zdr_xl eq '6'?"selected='selected'":''}>硕士</option>
								<option value="7" ${pd.zdr_xl eq '7'?"selected='selected'":''}>博士及以上</option>							
								</select>
				</div>
			</div>

			    <div class="form-group">
			    <label class="col-sm-2 control-label">现住地址<i class="red">*</i></label>
				<div class="col-sm-8">
				   <input id="zdr_xzdz" name="zdr_xzdz" type="text"  value="${pd.zdr_xzdz }" class="form-control">
				</div>

		        </div>
<!-- 		        <div class="form-group">
				<label class="col-sm-2 control-label">详细住址<i class="red">*</i></label>
				<div class="col-sm-8">
				   <input class="form-control ng-pristine ng-untouched ng-valid ng-not-empty" name="presentAddress" ng-model="data.presentAddress"  required="required" type="text">
				</div>
				</div> -->
		        <div class="form-group">
				<label class="col-sm-2 control-label">邮编<i class="red">*</i></label>
				<div class="col-sm-3">
				   <input class="form-control " name="zdr_yzbm"  id="zdr_yzbm" value="${pd.zdr_yzbm }" type="text">
				</div>
				 <label class="col-sm-2 control-label">居住壮况<i class="red">*</i></label>
				<div class="col-sm-3">
	            <select id="zdr_jzzk" name="zdr_jzzk" class="form-control" tabindex="-1">
			    <option value="-1">请选择</option>
			    <option value="0" ${pd.zdr_jzzk eq '0'?"selected='selected'":''}>自有住房</option>
			    <option value="1" ${pd.zdr_jzzk eq '1'?"selected='selected'":''}>租房</option>
			    <option value="2" ${pd.zdr_jzzk eq '2'?"selected='selected'":''}>分期付款购房</option>
			    <option value="3" ${pd.zdr_jzzk eq '3'?"selected='selected'":''}>集体宿舍</option>
			    <option value="4" ${pd.zdr_jzzk eq '4'?"selected='selected'":''}>其他</option>							
			    </select>
		        </div>
		        </div>
		        <div class="form-group">
		      	<label class="col-sm-2 control-label">现住电话<i class="red">*</i></label>
				<div class="col-sm-3">
				 <input class="form-control "  value="${pd.zdr_dwdh  }" type="text">
				</div>
				<label class="col-sm-2 control-label">单位电话<i class="red">*</i></label>
				<div class="col-sm-3">
				   <input class="form-control" value="${pd.zdr_dwdh  }" type="text">
				</div>
		        </div>

		    <div class="form-group">
				<label class="col-sm-2 control-label">工作单位<i class="red">*</i></label>
				<div class="col-sm-8">
				  <input class="form-control" name="zdr_gzdw" value="${pd.zdr_gzdw} " type="text">
				</div> 
		    </div>
		    <div class="form-group">
				<label class="col-sm-2 control-label">单位地址<i class="red">*</i></label>
				<div class="col-sm-8">
				   <input class="form-control" name="zdr_dwdz" value="${pd.zdr_dwdz }" type="text">
				</div>
		    </div>
		    <div class="form-group">
		       <label class="col-sm-2 control-label">单位性质<i class="red">*</i></label>
			   <div class="col-sm-8">
	      	   <select class="form-control" name="zdr_dwxz" id="zdr_dwxz">
				<option value="-1">请选择</option>
				<option value="0" ${pd.zdr_dwxz eq '0'?"selected='selected'":''}>国有</option>
				<option value="1" ${pd.zdr_dwxz eq '1'?"selected='selected'":''}>集体经济</option>
				<option value="2" ${pd.zdr_dwxz eq '2'?"selected='selected'":''}>私营</option>
				<option value="3" ${pd.zdr_dwxz eq '3'?"selected='selected'":''}>民营</option>
				<option value="4" ${pd.zdr_dwxz eq '4'?"selected='selected'":''}>股份合作</option>
				<option value="5" ${pd.zdr_dwxz eq '5'?"selected='selected'":''}>其他股份制</option>
				<option value="6" ${pd.zdr_dwxz eq '6'?"selected='selected'":''} >个体</option>
				<option value="7" ${pd.zdr_dwxz eq '7'?"selected='selected'":''}>三资</option>
				<option value="8" ${pd.zdr_dwxz eq '8'?"selected='selected'":''}>其他</option>	
			   <!-- <label class="col-sm-2 control-label">单位规模<i class="red">*</i></label>
			   <div class="col-sm-3">
			        <select class="form-control"  name="">
			        <option value="" class="ng-binding" selected="selected">--请选择--</option>
			        <option label="地市级单位大型企业1亿以上" value="" >地市级单位大型企业1亿以上</option>
			        <option label="县市级单位中型企业0.1-1亿" value="">县市级单位中型企业0.1-1亿</option>
			        <option label="镇级单位一般企业100-1000万" value="">镇级单位一般企业100-1000万</option>
			        <option label="小型企业10-100万" value="">小型企业10-100万</option>
			        <option label="微型企业10万以下" value="">微型企业10万以下</option>
			        </select>
			   </div> -->
	      	   </select>
			</div>
		    </div>
		    <div class="form-group">
			<label class="col-sm-2 control-label">职业<i class="red">*</i></label>
			<div class="col-sm-3">
	      	   <select class="form-control" id="zdr_zy" name="zdr_zy">
						<option value="-1">请选择</option>
						<option  value="0" ${pd.zdr_zy eq '0'?"selected='selected'":''}>公务员</option>
						<option value="1" ${pd.zdr_zy eq '1'?"selected='selected'":''}>事业单位员工</option>
						<option value="2" ${pd.zdr_zy eq '2'?"selected='selected'":''}>工人</option>
						<option value="3" ${pd.zdr_zy eq '3'?"selected='selected'":''}>农民</option>
						<option value="4" ${pd.zdr_zy eq '4'?"selected='selected'":''}>军人</option>
						<option value="5" ${pd.zdr_zy eq '5'?"selected='selected'":''}>职员</option>
						<option value="6" ${pd.zdr_zy eq '6'?"selected='selected'":''}>私人业主</option>
						<option value="7" ${pd.zdr_zy eq '7'?"selected='selected'":''}>学生</option>
						<option value="8" ${pd.zdr_zy eq '8'?"selected='selected'":''}>自由职业</option>
						<option value="9" ${pd.zdr_zy eq '9'?"selected='selected'":''}>其他</option>	
	      	   </select>
			</div>
			<label class="col-sm-2 control-label">职务<i class="red">*</i></label>
			<div class="col-sm-3">
	      	   <select class="form-control " name="zdr_zw"  id="zdr_zw">
						<option value="-1">请选择</option>
						<option value="0" ${pd.zdr_zw eq '0'?"selected='selected'":''}>企业负责人</option>
						<option value="1" ${pd.zdr_zw eq '1'?"selected='selected'":''}>总经理</option>
						<option value="2" ${pd.zdr_zw eq '2'?"selected='selected'":''}>部门经理</option>
						<option value="3" ${pd.zdr_zw eq '3'?"selected='selected'":''}>职员</option>
                </select>
			</div>
	    </div>
	    <div class="form-group">
	    	<label class="col-sm-2 control-label">月收入(元)<i class="red">*</i></label>
			<div class="col-sm-3">
			   <input class="form-control " id="zdr_grsr" name="zdr_grsr"  value="${pd.zdr_grsr }"   type="number">
			</div>
			<label class="col-sm-2 control-label lablewidth">工作年限(年)<i class="red">*</i></label>
			<div class="col-sm-3">
			   <input class="form-control " name="zdr_gznx" id="zdr_gznx" value="${pd.zdr_gznx }" type="number">
			</div>
			
	    </div>
	     <div class="form-group">
	        <label class="col-sm-2 control-label lablewidth">文书送达地址<i class="red">*</i></label>
			<div class="col-sm-8">
			   <input  class="form-control" id="zdr_wsdz" name="zdr_wsdz" value="${pd.zdr_wsdz }"  title="送达地址"   type="text">
			</div>
	     </div>
        <div class="form-group">
			<label class="col-sm-2 control-label">
			<a  onclick="hzpdf('${pd.id}')"  class="btn btn-primary ng-binding" >生成合同文件</a>
			</label>
	  		<div class="col-sm-3">
	  		 <c:if test="${!empty pd.pdf }">
	  		 <a target="_blank"  href="http://a.kcway.net/assess/${pd.pdf }">
	  		 <img  id="ht_pdf" name="ht_pdf" class="thumbnail" style="width: 100px;height: 100px;" onclick=""  src="${pageContext.request.contextPath }/kjs_icbc/kjs_icbc_style/images/301175241676158600.png">
	  		 </a>
	  		 </c:if>
		     <c:if test="${empty pd.pdf }">
		     <a onclick="alert('暂无PDF文件!!!');">
		     <img   id="ht_pdf" name="ht_pdf" class="thumbnail" style="width: 100px;height: 100px;" onclick=""  src="${pageContext.request.contextPath }/kjs_icbc/kjs_icbc_style/images/logo.png">
             </a>
		     </c:if>
		     </div>
		     <label class="col-sm-2 control-label">
			 <a   onclick="addexcel('${pd.id}')"  class="btn btn-primary ng-binding" >生成Excel文件</a>
			 </label>
	  		 <div class="col-sm-3">
	  		 <c:if test="${!empty pd.excel }">
	  		 <a target="_blank" href="http://a.kcway.net/assess/${pd.excel }">
	  		 <img   id="excel_pdf" name="excel_pdf" class="thumbnail" style="width: 100px;height: 100px;" onclick=""  src="${pageContext.request.contextPath }/kjs_icbc/kjs_icbc_style/images/301175241676158600.png">
	  		 </a>
	  		 </c:if>
		     <c:if test="${empty pd.excel }">
		      <a onclick="alert('暂无Excel文件!!!');">
		     <img  id="excel_pdf" name="excel_pdf" class="thumbnail" style="width: 100px;height: 100px;" onclick=""  src="${pageContext.request.contextPath }/kjs_icbc/kjs_icbc_style/images/logo.png">
		      </a>
		     </c:if>
		     </div>
		</div>
	    </div>
	    <script type="text/javascript">
	    function addexcel(id) {
	    	  $.ajax({
	    		   type:'POST',   
	    		   url:'${pageContext.request.contextPath}/icbc/excel.do',
	    		   dataType:'json',
	    		   data:{
	    			   id : id
	    		   },
	    	  success: function(msg){
	    		 if(msg.code==1){
	    			alert("Excel生成成功!");
	    			window.location.reload();
	    		 }else{
	    			alert("Excel生成失败;"+msg.message); 
	    		 } 		  
	    		},
	  		error:function(){
	  		   alert("系统错误,请稍后重试...");         
	  		}
	    	  });
	       }	    
	    function hzpdf(id) {
	  	  $.ajax({
	  		   type:'POST',   
	  		   url:'${pageContext.request.contextPath}/icbc/ptreating.do',
	  		   dataType:'json',
	  		   data:{
	  			   id : id
	  		   },
	  	  success: function(msg){
	  		 if(msg.code==1){
	  			alert("合同生成成功!");
	  			window.location.reload();
	  		 }else{
	  			alert("合同生成失败;"+msg.message); 
	  		 } 		  
	  		},
			error:function(){
			   alert("系统错误,请稍后重试...");         
			}
	  	  });
	     }
	    </script>
	</form>
    </div>
    <div class="tab-pane fade" id="ghr">
      <form name="modalForm" class="form-horizontal">
      <c:if test="${empty requestScope.ghrlist }">
       <div style="border:1px solid #478FCA;   margin:5px; padding:20px;border-radius: 10px;"> 
      <div class="form-group">
			<label class="col-sm-2 control-label">姓名<i class="red">*</i></label>
	  		<div class="col-sm-3">
	      	   <input class="form-control " id="name" name="name" value="" type="text">
			</div>
			<label class="col-sm-2 control-label">关系<i class="red">*</i></label>
			<div class="col-sm-3">
			<input id="yzdrgx" name="yzdrgx"  class="form-control" value="" type="text" />
	      	</div>
		</div>
		<div class="form-group">
			<label class="col-sm-2 control-label"><span class="red">*</span>月收入(元)</label>
			<div class="col-sm-3">
             <input class="form-control " id="ysr" name="ysr" value=""  type="text">
            </div>
            <label class="col-sm-2 control-label"><span class="red">*</span>学历</label>
			<div class="col-sm-3">
            <select id="xl" name="xl" class="form-control" tabindex="-1">
			<option  value="0">请选择</option>
			<option value="1" >小学</option>
			<option value="2" >初中</option>
			<option value="3" >高中</option>
			<option value="4" >大专</option>
			<option value="5" >本科</option>
			<option value="6" >硕士</option>
			<option value="7" >博士及以上</option>	
			</select>
            </div>
		</div>
				<div class="form-group">
			<label class="col-sm-2 control-label"><span class="red">*</span>现住地址</label>
			<div class="col-sm-3">
             <input class="form-control "  id="xzdz" name="xzdz" value="" type="text">
            </div>
            <label class="col-sm-2 control-label"><span class="red">*</span>邮政编码</label>
			<div class="col-sm-3">
			<input class="form-control"  id="yzbm" name="yzbm"  value=""  type="text"/> 
                 </div>
		</div>
						<div class="form-group">
			<label class="col-sm-2 control-label"><span class="red">*</span>工作单位</label>
			<div class="col-sm-3">
             <input class="form-control" id="gzdw" name="gzdw"  value="" type="text">
            </div>
            <label class="col-sm-2 control-label"><span class="red">*</span>单位地址</label>
			<div class="col-sm-3">
			<input class="form-control"  id="dwdz" name="dwdz"  value="" type="text"/> 
                 </div>
		</div>
		<div class="form-group">
			<label class="col-sm-2 control-label"><span class="red">*</span>文书送达地址</label>
			<div class="col-sm-3">
             <input class="form-control"  id="wsdz" name="wsdz" value="" type="text">
            </div>
            <label class="col-sm-2 control-label"><span class="red">*</span>主要从事或职务</label>
			<div class="col-sm-3">
			<input class="form-control"  id="zw" name="zw"  value=""  type="text"/> 
                 </div>
		</div>
		<div class="form-group">
			<label class="col-sm-2 control-label">联系人级别</label>
			<div class="col-sm-3">
				<select class="form-control" >
				<option value="">--请选择--</option>
				<option value="">主要联系人</option>
				<option value="">次要联系人</option>
				<option value="">其他</option>
				</select>
			</div>
			<label class="col-sm-2 control-label">联系人电话区号</label>
			<div class="col-sm-3">
				<input class="form-control"  type="text">
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-2 control-label">手机号码<i class="red">*</i></label>
			<div class="col-sm-3">
				<input class="form-control" id="tel" name="tel"  value=""  type="text">
			</div>
			<label class="col-sm-2 control-label"><span class="red">*</span>性别</label>
			<div class="col-sm-3">
			<select id="" name="" class="form-control">
			<option value="0">--请选择--</option>
			<option value="1">男</option>
			<option value="2">女</option>
			</select>
			</div>
		</div>
			<div class="form-group">
			<label class="col-sm-2 control-label">婚姻状况<i class="red">*</i></label>
			<div class="col-sm-3">
				<select id="hyzk" name="hyzk" class="form-control" tabindex="-1">
				<option value="-1">请选择</option>
				<option value="0" >未婚</option>
				<option value="1" >已婚</option>
				<option value="2" >离异</option>
				<option value="3" >丧偶</option>							
				</select>	
				</div>
			<label class="col-sm-2 control-label">身份证号<i class="red">*</i></label>
			<div class="col-sm-3">
			 <input  class="form-control" id="cardno" name="cardno" value="" />	
		    </div>	
		</div>
		</div>
      </c:if>
       <c:forEach  var="ghr" items="${requestScope.ghrlist }">
       <div style="border:1px solid #478FCA;   margin:5px; padding:20px;border-radius: 10px;"> 
      <div class="form-group">
			<label class="col-sm-2 control-label">姓名<i class="red">*</i></label>
	  		<div class="col-sm-3">
	      	   <input class="form-control " id="name" name="name" value="${ghr.name }" type="text">
			</div>
			<label class="col-sm-2 control-label">关系<i class="red">*</i></label>
			<div class="col-sm-3">
			<input id="yzdrgx" name="yzdrgx"  class="form-control" value="${ghr.yzdrgx }" type="text" />
	      	</div>
		</div>
		<div class="form-group">
			<label class="col-sm-2 control-label"><span class="red">*</span>月收入(元)</label>
			<div class="col-sm-3">
             <input class="form-control " id="ysr" name="ysr" value="${ghr.ysr }"  type="text">
            </div>
            <label class="col-sm-2 control-label"><span class="red">*</span>学历</label>
			<div class="col-sm-3">
            <select id="xl" name="xl" class="form-control" tabindex="-1">
			<option  value="0">请选择</option>
			<option value="1" ${ghr.xl eq '1'?"selected='selected'":''}>小学</option>
			<option value="2" ${ghr.xl eq '2'?"selected='selected'":''}>初中</option>
			<option value="3" ${ghr.xl eq '3'?"selected='selected'":''}>高中</option>
			<option value="4" ${ghr.xl eq '4'?"selected='selected'":''}>大专</option>
			<option value="5" ${ghr.xl eq '5'?"selected='selected'":''}>本科</option>
			<option value="6" ${ghr.xl eq '6'?"selected='selected'":''}>硕士</option>
			<option value="7" ${ghr.xl eq '7'?"selected='selected'":''}>博士及以上</option>	
			</select>
            </div>
		</div>
				<div class="form-group">
			<label class="col-sm-2 control-label"><span class="red">*</span>现住地址</label>
			<div class="col-sm-3">
             <input class="form-control "  id="xzdz" name="xzdz" value="${ghr.xzdz }" type="text">
            </div>
            <label class="col-sm-2 control-label"><span class="red">*</span>邮政编码</label>
			<div class="col-sm-3">
			<input class="form-control"  id="yzbm" name="yzbm"  value="${ghr.yzbm }"  type="text"/> 
                 </div>
		</div>
						<div class="form-group">
			<label class="col-sm-2 control-label"><span class="red">*</span>工作单位</label>
			<div class="col-sm-3">
             <input class="form-control" id="gzdw" name="gzdw"  value="${ghr.gzdw }" type="text">
            </div>
            <label class="col-sm-2 control-label"><span class="red">*</span>单位地址</label>
			<div class="col-sm-3">
			<input class="form-control"  id="dwdz" name="dwdz"  value="${ghr.dwdz }" type="text"/> 
                 </div>
		</div>
		<div class="form-group">
			<label class="col-sm-2 control-label"><span class="red">*</span>文书送达地址</label>
			<div class="col-sm-3">
             <input class="form-control"  id="wsdz" name="wsdz" value="${ghr.wsdz }" type="text">
            </div>
            <label class="col-sm-2 control-label"><span class="red">*</span>主要从事或职务</label>
			<div class="col-sm-3">
			<input class="form-control"  id="zw" name="zw"  value="${ghr.zw }"  type="text"/> 
                 </div>
		</div>
		<div class="form-group">
			<label class="col-sm-2 control-label">联系人级别</label>
			<div class="col-sm-3">
				<select class="form-control" >
				<option value="">--请选择--</option>
				<option value="">主要联系人</option>
				<option value="">次要联系人</option>
				<option value="">其他</option>
				</select>
			</div>
			<label class="col-sm-2 control-label">联系人电话区号</label>
			<div class="col-sm-3">
				<input class="form-control"  type="text">
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-2 control-label">手机号码<i class="red">*</i></label>
			<div class="col-sm-3">
				<input class="form-control" id="tel" name="tel"  value="${ghr.tel }"  type="text">
			</div>
			<label class="col-sm-2 control-label"><span class="red">*</span>性别</label>
			<div class="col-sm-3">
			<select id="" name="" class="form-control">
			<option value="0">--请选择--</option>
			<option value="1">男</option>
			<option value="2">女</option>
			</select>
			</div>
		</div>
			<div class="form-group">
			<label class="col-sm-2 control-label">婚姻状况<i class="red">*</i></label>
			<div class="col-sm-3">
				<select id="hyzk" name="hyzk" class="form-control" tabindex="-1">
				<option value="-1">请选择</option>
				<option value="0" ${ghr.hyzk eq '0'?"selected='selected'":''}>未婚</option>
				<option value="1" ${ghr.hyzk eq '1'?"selected='selected'":''}>已婚</option>
				<option value="2" ${ghr.hyzk eq '2'?"selected='selected'":''}>离异</option>
				<option value="3" ${ghr.hyzk eq '3'?"selected='selected'":''}>丧偶</option>							
				</select>	
				</div>
			<label class="col-sm-2 control-label">身份证号<i class="red">*</i></label>
			<div class="col-sm-3">
			 <input  class="form-control" id="cardno" name="cardno" value="${ghr.cardno }" />	
		    </div>	
		</div>
		</div>
</c:forEach>
      </form>
    </div>
	<div class="tab-pane fade" id="qtlxr">
		<form name="modalForm" class="form-horizontal">
		<div style="border:1px solid #478FCA;   margin:5px; padding:20px;border-radius: 10px;"> 
		    <strong>亲属</strong> 
			<div class="form-group">
			<label class="col-sm-2 control-label">姓名<i class="red">*</i></label>
			<div class="col-sm-3">
				<input class="form-control" id="jjlxr_c_name" name="jjlxr_c_name"  value="${pd.jjlxr_c_name }"  type="text">
			</div>
			<label class="col-sm-2 control-label"><span class="red">*</span>电话</label>
			<div class="col-sm-3">
			<input class="form-control" id="jjlxr_c_tel" name="jjlxr_c_tel" value="${pd.jjlxr_c_tel }" type="text">
	
			</div>
		   </div>
		
			<div class="form-group">
			
			<label class="col-sm-2 control-label">与主贷人关系<i class="red">*</i></label>
			<div class="col-sm-3">
				<input class="form-control "  id="jjlxr_jdrgx"  name="jjlxr_jdrgx" value="${pd.jjlxr_jdrgx }" type="text">
			</div>
			<label class="col-sm-2 control-label"><span class="red">*</span>现住地址</label>
			<div class="col-sm-3">
			<input class="form-control"  id="jjlxr_xzdz"  name="jjlxr_xzdz" value="${pd.jjlxr_xzdz }" type="text">
	
			</div>
		    </div>
		
		</div>
				<div style="border:1px solid #478FCA;   margin:5px; padding:20px;border-radius: 10px;"> 
				<strong>其他</strong> 
				<div class="form-group">
			<label class="col-sm-2 control-label">姓名<i class="red">*</i></label>
			<div class="col-sm-3">
				<input class="form-control" id="jjlxr_c_name" name="jjlxr_c_name"  value="${pd.qtlxr_c_name }"  type="text">
			</div>
			<label class="col-sm-2 control-label"><span class="red">*</span>电话</label>
			<div class="col-sm-3">
			<input class="form-control" id="jjlxr_c_tel" name="jjlxr_c_tel" value="${pd.qtlxr_c_tel  }" type="text">
	
			</div>
		</div>
		
					<div class="form-group">
			<label class="col-sm-2 control-label">与主贷人关系<i class="red">*</i></label>
			<div class="col-sm-3">
				<input class="form-control "  id="jjlxr_jdrgx"  name="jjlxr_jdrgx" value="${pd.qtlxr_jdrgx }" type="text">
			</div>
			<label class="col-sm-2 control-label"><span class="red">*</span>现住地址</label>
			<div class="col-sm-3">
			<input class="form-control"  id="jjlxr_xzdz"  name="jjlxr_xzdz" value="${pd.qtlxr_xzdz }" type="text">
	
			</div>
		</div>
		
		</div>
<!-- 				<div style="border:1px solid #478FCA;   margin:5px; padding:5px 0 2px 0;border-radius: 10px;"> 
				<div class="form-group">
			<label class="col-sm-2 control-label">姓名<i class="red">*</i></label>
			<div class="col-sm-3">
				<input class="form-control "  pattern="^[1][3456789][0-9]{9}$" maxlength="11" ng-required="true"  required="required" type="text">
			</div>
			<label class="col-sm-2 control-label"><span class="red">*</span>电话</label>
			<div class="col-sm-3">
			<input class="form-control "  pattern="^[1][3456789][0-9]{9}$" maxlength="11" ng-required="true"  required="required" type="text">
	
			</div>
		</div>
		
					<div class="form-group">
			<label class="col-sm-2 control-label">与主贷人关系<i class="red">*</i></label>
			<div class="col-sm-3">
				<input class="form-control "  pattern="^[1][3456789][0-9]{9}$" maxlength="11" ng-required="true"  required="required" type="text">
			</div>
			<label class="col-sm-2 control-label"><span class="red">*</span>现住地址</label>
			<div class="col-sm-3">
			<input class="form-control "  pattern="^[1][3456789][0-9]{9}$" maxlength="11" ng-required="true"  required="required" type="text">
	
			</div>
		</div>
		
		</div> -->
		</form>
	</div>

	<div class="tab-pane fade" id="srxx">
      <form action="" class="form-horizontal">
     				<div style="border:1px solid #478FCA;   margin:5px; padding:20px;border-radius: 10px;"> 
				<div class="form-group">
			<label class="col-sm-2 control-label">收入类型<i class="red">*</i></label>
			<div class="col-sm-3">
			<select class="form-control">
			<option value="" selected="selected">--请选择--</option>
			<option label="未知" value="">未知</option>
			<option label="工资性收入" value="">工资性收入</option>
			<option label="租赁收入" value="">租赁收入</option>
			<option label="经营性收入" value="">经营性收入</option>
			<option label="其他收入" value="">其他收入</option>
			</select>	
			</div>
			<label class="col-sm-2 control-label"><span class="red">*</span>收入币种</label>
			<div class="col-sm-3">
			<select class="form-control"  >
			<option value=""  selected="selected">--请选择--</option>
			<option label="人民币" value="" >人民币</option>
			<option label="美元" value="">美元</option>
			<option label="欧元" value="">欧元</option>
			<option label="其他" value="">其他</option>
			</select>
			</div>
		</div>
	<div class="form-group">
			<label class="col-sm-2 control-label">月收入(元)<i class="red">*</i></label>
			<div class="col-sm-3">
				<input class="form-control" id="zdr_grsr" name="zdr_grsr" value="${pd.zdr_grsr }" type="text">
			</div>
			<label class="col-sm-2 control-label">家庭月收入(元)<i class="red">*</i></label>
			<div class="col-sm-3">
				<input class="form-control" id="zdr_jtsr" name="zdr_jtsr" value="${pd.zdr_jtsr }" type="text">
			</div>
		</div>
     </div>
     </form>
    </div>
    
<div class="tab-pane fade" id="jtxx">
    <form action="" class="form-horizontal">
     				<div style="border:1px solid #478FCA;   margin:5px; padding:20px;border-radius: 10px;"> 
				<div class="form-group">
			<label class="col-sm-2 control-label">家庭月收入(元)<i class="red">*</i></label>
			<div class="col-sm-3">
				<input class="form-control " id="zdr_jtsr" name="zdr_jtsr" value="${pd.zdr_jtsr }"  type="text">
			</div>
			<label class="col-sm-2 control-label"><span class="red">*</span>供养人数</label>
			<div class="col-sm-3">
			<input class="form-control "  id="" name="" value=""  type="text">
	
			</div>
		</div>
		
					<div class="form-group">
			<label class="col-sm-2 control-label">人均月收入(元)<i class="red">*</i></label>
			<div class="col-sm-3">
				<input class="form-control "  pattern="^[1][3456789][0-9]{9}$" maxlength="11" ng-required="true"  required="required" type="text">
			</div>
			<label class="col-sm-2 control-label"><span class="red">*</span>月负债(万元)</label>
			<div class="col-sm-3">
			<input class="form-control "  pattern="^[1][3456789][0-9]{9}$" maxlength="11" ng-required="true"  required="required" type="text">
	
			</div>
		</div>
							<div class="form-group">
			<label class="col-sm-2 control-label">净资产(元)<i class="red">*</i></label>
			<div class="col-sm-3">
				<input class="form-control "  pattern="^[1][3456789][0-9]{9}$" maxlength="11" ng-required="true"  required="required" type="text">
			</div>
			<label class="col-sm-2 control-label"><span class="red">*</span>负债(元)</label>
			<div class="col-sm-3">
			<input class="form-control "  pattern="^[1][3456789][0-9]{9}$" maxlength="11" ng-required="true"  required="required" type="text">
	
			</div>
		</div>
									<div class="form-group">
			<label class="col-sm-2 control-label">净资产贷款比<i class="red">*</i></label>
			<div class="col-sm-3">
				<input class="form-control "  pattern="^[1][3456789][0-9]{9}$" maxlength="11" ng-required="true"  required="required" type="text">
			</div>
			<label class="col-sm-2 control-label"><span class="red">*</span>年均存款(元)</label>
			<div class="col-sm-3">
			<input class="form-control "  pattern="^[1][3456789][0-9]{9}$" maxlength="11" ng-required="true"  required="required" type="text">
	
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-2 control-label">人均住房面积(平方)<i class="red">*</i></label>
			<div class="col-sm-3">
				<input class="form-control "  pattern="^[1][3456789][0-9]{9}$" maxlength="11" ng-required="true"  required="required" type="text">
			</div>
			<label class="col-sm-2 control-label"><span class="red">*</span>住房存款净值(万元)</label>
			<div class="col-sm-3">
			<input class="form-control "  pattern="^[1][3456789][0-9]{9}$" maxlength="11" ng-required="true"  required="required" type="text">
	
			</div>
		</div>
				<div class="form-group">
			<label class="col-sm-2 control-label">有价证券净值(万元)<i class="red">*</i></label>
			<div class="col-sm-3">
				<input class="form-control "  pattern="^[1][3456789][0-9]{9}$" maxlength="11" ng-required="true"  required="required" type="text">
			</div>
			<label class="col-sm-2 control-label"><span class="red">*</span>实物资产净值(万元)</label>
			<div class="col-sm-3">
			<input class="form-control "  pattern="^[1][3456789][0-9]{9}$" maxlength="11" ng-required="true"  required="required" type="text">
	
			</div>
		</div>
						<div class="form-group">
			<label class="col-sm-2 control-label">对外投资净值(万元)<i class="red">*</i></label>
			<div class="col-sm-3">
				<input class="form-control "  pattern="^[1][3456789][0-9]{9}$" maxlength="11" ng-required="true"  required="required" type="text">
			</div>
			<label class="col-sm-2 control-label"><span class="red">*</span>自建房净值(万元)</label>
			<div class="col-sm-3">
			<input class="form-control "  pattern="^[1][3456789][0-9]{9}$" maxlength="11" ng-required="true"  required="required" type="text">
	
			</div>
		</div>
		</div>
     </form>
    </div>
    
     <div class="tab-pane fade" id="fcxx">
       <form action="" class="form-horizontal">
     	<div style="border:1px solid #478FCA;   margin:5px; padding:20px;border-radius: 10px;"> 
<div class="form-group" cg-disabled="detail,create">
			<label class="col-sm-2 control-label">房屋权属人<i class="red">*</i></label>
	  		<div class="col-sm-3">
	      	   <input class="form-control ng-pristine ng-untouched ng-valid ng-empty" name="houseOwner" ng-model="item.houseOwner"  required="required" disabled="disabled" type="text">
			</div>
			<label class="col-sm-2 control-label">关系<i class="red">*</i></label>
			<div class="col-sm-3">
	      	   <select class="form-control ng-isolate-scope ng-empty ng-valid" ng-options="opt.realValue as opt.displayValue for opt in options" ng-model="item.ownerRelation" name="ownerRelation" index="HOUSE_RELATION" source="resources"  required="required" disabled="disabled"><option value="" class="ng-binding" selected="selected">--请选择--</option><option label="个人" value="string:个人">个人</option><option label="父子" value="string:父子">父子</option><option label="母子" value="string:母子">母子</option><option label="兄弟姐妹" value="string:兄弟姐妹">兄弟姐妹</option><option label="亲属" value="string:亲属">亲属</option><option label="夫妻" value="string:夫妻">夫妻</option><option label="同学" value="string:同学">同学</option><option label="同乡" value="string:同乡">同乡</option><option label="朋友" value="string:朋友">朋友</option><option label="同事" value="string:同事">同事</option><option label="共还人配偶" value="string:共还人配偶">共还人配偶</option><option label="其他" value="string:其他">其他</option></select>
			</div>
		</div>
<div class="form-group" cg-disabled="detail,create">
			<label class="col-sm-2 control-label">产权证号</label>
			<div class="col-sm-3">
				<input class="form-control ng-pristine ng-untouched ng-valid ng-empty" name="propertyNum" ng-model="item.propertyNum" disabled="disabled" type="text">
			</div>
			<label class="col-sm-2 control-label">是否共有资产</label>
			<div class="col-sm-3">
				<input value="1" ng-model="item.isShared" ng-checked="true" class="ng-pristine ng-untouched ng-valid ng-not-empty" name="2774" disabled="disabled" checked="checked" type="radio">是
	            &nbsp;&nbsp;&nbsp;&nbsp;
	            <input value="0" ng-model="item.isShared" class="ng-pristine ng-untouched ng-valid ng-not-empty" name="2775" disabled="disabled" type="radio">否
			</div>
		</div>
		<div class="form-group" cg-disabled="detail,create">
			<label class="col-sm-2 control-label">建购价格(万)<i class="red">*</i></label>
			<div class="col-sm-3">
				<input class="form-control ng-pristine ng-untouched ng-valid ng-empty ng-valid-pattern" name="buildPrice" ng-model="item.buildPrice" cg-formatter="toTenThousand"  pattern="^\d{0,8}\.{0,1}(\d{1,6})?$" required="required" disabled="disabled" type="text">
			</div>
			<label class="col-sm-2 control-label">所占份额(%)</label>
			<div class="col-sm-3">
				<input class="form-control ng-pristine ng-untouched ng-valid ng-empty ng-valid-pattern" name="shareRatio" ng-model="item.shareRatio" pattern="^\d{0,8}\.{0,1}(\d{1,2})?$" disabled="disabled" type="text">
			</div>
		</div>
		<div class="form-group" cg-disabled="detail,create">
			<label class="col-sm-2 control-label">房屋性质<i class="red">*</i></label>
			<div class="col-sm-3">
				<select class="form-control ng-isolate-scope ng-empty ng-valid" ng-options="opt.realValue as opt.displayValue for opt in options" ng-model="item.houseType" name="houseType" index="HOUSE_TYPE" source="resources"  required="required" disabled="disabled"><option value="" class="ng-binding" selected="selected">--请选择--</option><option label="自有住房" value="number:1">自有住房</option><option label="分期付款购房" value="number:2">分期付款购房</option><option label="租房" value="number:3">租房</option><option label="其他" value="number:4">其他</option><option label="集体宿舍" value="number:5">集体宿舍</option><option label="单位分配" value="number:6">单位分配</option></select>
			</div>
			<label class="col-sm-2 control-label">房屋面积(平方)<i class="red">*</i></label>
			<div class="col-sm-3">
				<input class="form-control ng-pristine ng-untouched ng-valid ng-empty ng-valid-pattern" name="houseSpace" ng-model="item.houseSpace"  pattern="^\d{0,8}\.{0,1}(\d{1,2})?$" required="required" disabled="disabled" type="text">
			</div>
		</div>
		<div class="form-group" cg-disabled="detail,create">
			<label class="col-sm-2 control-label">房屋地址<i class="red">*</i></label>
			<div class="col-sm-3">
				<input class="form-control ng-pristine ng-untouched ng-valid ng-empty" name="houseAddress" ng-model="item.houseAddress"  required="required" disabled="disabled" type="text">
			</div>
			<label class="col-sm-2 control-label">房产抵押情况</label>
			<div class="col-sm-3">
				<input value="1" ng-model="item.isPledged" ng-checked="true" class="ng-pristine ng-untouched ng-valid ng-not-empty" name="2777" disabled="disabled" checked="checked" type="radio">有抵押
	            &nbsp;&nbsp;&nbsp;&nbsp;
	            <input value="0" ng-model="item.isPledged" class="ng-pristine ng-untouched ng-valid ng-not-empty" name="2778" disabled="disabled" type="radio">无抵押
			</div>
		</div>
		<div class="form-group" cg-disabled="detail,create">
			<label class="col-sm-2 control-label">买入日期<i class="red">*</i></label>
			<div class="col-sm-3">
				<div class="input-group date ng-isolate-scope ng-empty ng-valid" ng-model="item.buyDate"  required="required">
  <input class="form-control" disabled="disabled" type="text"><span class="input-group-addon"><i class="fa fa-calendar"></i></span>
</div>
			</div>
			<label class="col-sm-2 control-label">评估价格(万)</label>
			<div class="col-sm-3">
				<input class="form-control ng-pristine ng-untouched ng-valid ng-empty ng-valid-pattern" name="evaluatePrice" ng-model="item.evaluatePrice" pattern="^\d{0,8}\.{0,1}(\d{1,2})?$" cg-formatter="toTenThousand" disabled="disabled" type="text">
			</div>
		</div>
		<div class="form-group" cg-disabled="detail,create">
			<label class="col-sm-2 control-label">购房欠款余额(万)</label>
			<div class="col-sm-3">
				<input class="form-control ng-pristine ng-untouched ng-valid ng-empty ng-valid-pattern" name="remainLoanAmount" ng-model="item.remainLoanAmount" pattern="^\d{0,8}\.{0,1}(\d{1,2})?$" cg-formatter="toTenThousand" disabled="disabled" type="text">
			</div>
		</div>
		
	</div>

	</form>
    </div>
    </div></div>
<c:if test="${requestScope.type!='wdrw' }">
<div class="modal-footer">
<button onclick="location.href='${pageContext.request.contextPath}/erp/user_list_.do?type=wlghd&dn=${requestScope.cn }&qn=list&pagesize=10&pagenow=1'" class="btn btn-warning" >取消</button>
<button onclick="location.href='" class="btn btn-primary" >提交</button>
</div>
</c:if>