package com.model.newAdd;
// Generated 2018-2-24 16:14:08 by Hibernate Tools 3.4.0.CR1

/**
 * BmsCpyclient generated by hbm2java
 */
public class BmsCpyclient implements java.io.Serializable {

	private Integer tid;
	private String tname;
	private Integer sex;
	private String tsumMany;
	private String cname;
	private String username;
	private String password;
	private String caddTime;
	private String cupdateTime;
	private String clientPhone;
	private String clientAddress;
	private String ta;
	private String tb;
	private String tc;
	private String td;
	private String te;
	private String tf;
	private String tg;
	private String th;
	private String ucid;    //  与  bmnuser表 中 uid 关联
	private Integer ctid;
	private Integer infoId;
	private int status;

	public BmsCpyclient() {
	}

	public BmsCpyclient(int status) {
		this.status = status;
	}

	public BmsCpyclient(String tname, Integer sex, String tsumMany, String cname, String username, String password,
			String caddTime, String cupdateTime, String clientPhone, String clientAddress, String ta, String tb,
			String tc, String td, String te, String tf, String tg, String th, String ucid, Integer ctid, Integer infoId,
			int status) {
		this.tname = tname;
		this.sex = sex;
		this.tsumMany = tsumMany;
		this.cname = cname;
		this.username = username;
		this.password = password;
		this.caddTime = caddTime;
		this.cupdateTime = cupdateTime;
		this.clientPhone = clientPhone;
		this.clientAddress = clientAddress;
		this.ta = ta;
		this.tb = tb;
		this.tc = tc;
		this.td = td;
		this.te = te;
		this.tf = tf;
		this.tg = tg;
		this.th = th;
		this.ucid = ucid;
		this.ctid = ctid;
		this.infoId = infoId;
		this.status = status;
	}

	public Integer getTid() {
		return this.tid;
	}

	public void setTid(Integer tid) {
		this.tid = tid;
	}

	public String getTname() {
		return this.tname;
	}

	public void setTname(String tname) {
		this.tname = tname;
	}

	public Integer getSex() {
		return this.sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	public String getTsumMany() {
		return this.tsumMany;
	}

	public void setTsumMany(String tsumMany) {
		this.tsumMany = tsumMany;
	}

	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getCaddTime() {
		return this.caddTime;
	}

	public void setCaddTime(String caddTime) {
		this.caddTime = caddTime;
	}

	public String getCupdateTime() {
		return this.cupdateTime;
	}

	public void setCupdateTime(String cupdateTime) {
		this.cupdateTime = cupdateTime;
	}

	public String getClientPhone() {
		return this.clientPhone;
	}

	public void setClientPhone(String clientPhone) {
		this.clientPhone = clientPhone;
	}

	public String getClientAddress() {
		return this.clientAddress;
	}

	public void setClientAddress(String clientAddress) {
		this.clientAddress = clientAddress;
	}

	public String getTa() {
		return this.ta;
	}

	public void setTa(String ta) {
		this.ta = ta;
	}

	public String getTb() {
		return this.tb;
	}

	public void setTb(String tb) {
		this.tb = tb;
	}

	public String getTc() {
		return this.tc;
	}

	public void setTc(String tc) {
		this.tc = tc;
	}

	public String getTd() {
		return this.td;
	}

	public void setTd(String td) {
		this.td = td;
	}

	public String getTe() {
		return this.te;
	}

	public void setTe(String te) {
		this.te = te;
	}

	public String getTf() {
		return this.tf;
	}

	public void setTf(String tf) {
		this.tf = tf;
	}

	public String getTg() {
		return this.tg;
	}

	public void setTg(String tg) {
		this.tg = tg;
	}

	public String getTh() {
		return this.th;
	}

	public void setTh(String th) {
		this.th = th;
	}

	public String getUcid() {
		return this.ucid;
	}

	public void setUcid(String ucid) {
		this.ucid = ucid;
	}

	public Integer getCtid() {
		return this.ctid;
	}

	public void setCtid(Integer ctid) {
		this.ctid = ctid;
	}

	public Integer getInfoId() {
		return this.infoId;
	}

	public void setInfoId(Integer infoId) {
		this.infoId = infoId;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
