package com.model.newAdd;
// Generated 2018-1-23 10:18:29 by Hibernate Tools 3.4.0.CR1

/**
 * BmsCompany generated by hbm2java
 */
public class BmsCompany implements java.io.Serializable {

	private Integer cid;
	private String cname;
	private String username;
	private String password;
	private String caddTime;
	private String cupdateTime;
	private Integer ucid;
	private Integer ctid;

	public BmsCompany() {
	}

	public BmsCompany(String cname, String username, String password, String caddTime, String cupdateTime, Integer ucid,
			Integer ctid) {
		this.cname = cname;
		this.username = username;
		this.password = password;
		this.caddTime = caddTime;
		this.cupdateTime = cupdateTime;
		this.ucid = ucid;
		this.ctid = ctid;
	}

	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getCaddTime() {
		return this.caddTime;
	}

	public void setCaddTime(String caddTime) {
		this.caddTime = caddTime;
	}

	public String getCupdateTime() {
		return this.cupdateTime;
	}

	public void setCupdateTime(String cupdateTime) {
		this.cupdateTime = cupdateTime;
	}

	public Integer getUcid() {
		return this.ucid;
	}

	public void setUcid(Integer ucid) {
		this.ucid = ucid;
	}

	public Integer getCtid() {
		return this.ctid;
	}

	public void setCtid(Integer ctid) {
		this.ctid = ctid;
	}

}
