package com.model.newAdd;
// Generated 2018-1-23 10:18:29 by Hibernate Tools 3.4.0.CR1

/**
 * BmsClientinfo generated by hbm2java
 */
public class BmsClientinfo implements java.io.Serializable {

	private Integer id;
	private String ca;
	private String cb;
	private String cc;
	private String cd;
	private Integer infoId;

	public BmsClientinfo() {
	}

	public BmsClientinfo(String ca, String cb, String cc, String cd, Integer infoId) {
		this.ca = ca;
		this.cb = cb;
		this.cc = cc;
		this.cd = cd;
		this.infoId = infoId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCa() {
		return this.ca;
	}

	public void setCa(String ca) {
		this.ca = ca;
	}

	public String getCb() {
		return this.cb;
	}

	public void setCb(String cb) {
		this.cb = cb;
	}

	public String getCc() {
		return this.cc;
	}

	public void setCc(String cc) {
		this.cc = cc;
	}

	public String getCd() {
		return this.cd;
	}

	public void setCd(String cd) {
		this.cd = cd;
	}

	public Integer getInfoId() {
		return this.infoId;
	}

	public void setInfoId(Integer infoId) {
		this.infoId = infoId;
	}

}
