package com.model.newAdd;
// Generated 2018-1-23 10:18:29 by Hibernate Tools 3.4.0.CR1

/**
 * BmsMenu generated by hbm2java
 */
public class BmsMenu implements java.io.Serializable {

	private Integer mid;
	private String mname;

	public BmsMenu() {
	}

	public BmsMenu(String mname) {
		this.mname = mname;
	}

	public Integer getMid() {
		return this.mid;
	}

	public void setMid(Integer mid) {
		this.mid = mid;
	}

	public String getMname() {
		return this.mname;
	}

	public void setMname(String mname) {
		this.mname = mname;
	}

}
