package com.model.newAdd;
// Generated 2018-1-23 10:18:29 by Hibernate Tools 3.4.0.CR1

/**
 * BmsUser generated by hbm2java
 */
public class BmsUser implements java.io.Serializable {

	private Integer uid;   // 与 BmsCpyclient表中 ucid 关联
	private String uname;
	private String username;
	private String password;
	private String userPhone;
	private String regTime;
	private String updateTime;
	private Integer upid;
	private Integer mid;
	private Integer deptno;
	private Integer ucid;   // 截至到 
	private Integer status; // 该账户   1可用      0不可用

	public BmsUser() {
	}

	public BmsUser(String uname, String username, String password, String regTime, String updateTime, Integer upid,
			Integer mid, Integer deptno, Integer ucid) {
		this.uname = uname;
		this.username = username;
		this.password = password;
		this.regTime = regTime;
		this.updateTime = updateTime;
		this.upid = upid;
		this.mid = mid;
		this.deptno = deptno;
		this.ucid = ucid;
	}
	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getUserPhone() {
		return userPhone;
	}

	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getRegTime() {
		return this.regTime;
	}

	public void setRegTime(String regTime) {
		this.regTime = regTime;
	}

	public String getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}

	public Integer getUpid() {
		return this.upid;
	}

	public void setUpid(Integer upid) {
		this.upid = upid;
	}

	public Integer getMid() {
		return this.mid;
	}

	public void setMid(Integer mid) {
		this.mid = mid;
	}

	public Integer getDeptno() {
		return this.deptno;
	}

	public void setDeptno(Integer deptno) {
		this.deptno = deptno;
	}

	public Integer getUcid() {
		return this.ucid;
	}

	public void setUcid(Integer ucid) {
		this.ucid = ucid;
	}

}
